### ISSUE TITLE
Recommended software for making a keybind?

### ISSUE THREAD

**Issue by Welding-Torch** [dynobo/normcap#103]
Like the title says, what's the recommended software for making a keybind? Asking because I'd like to use the least resource-consuming option possible. 

I'm on Windows 10.

**Comment by dynobo** [comment]
Hi, all the desktop operating systems I know have build-in solutions to create keybindings to open an application. Usually an internet search can help to find out how to do this.

E.g. for Windows 10 take a look [at this tutorial](https://www.cnet.com/how-to/open-programs-with-keyboard-shortcuts-in-windows-10/). It seems like you need to create an application shortcut to NormCap (if you used the installer, that should have created one already) and the define the keybinding in its properties.

Please let me know if that helps!

**Comment by Welding-Torch** [comment]
This is good, thanks!

Unrelated, but this app is probably the most useful utility that I've discovered this year. 
Keep up the good work
