### ISSUE TITLE
Not working on Debian Buster

### ISSUE THREAD

**Issue by liolio6** [dynobo/normcap#107]
Hello, I try to install normcap on debian Buster, the install work correctly but I got Segmentation fault when I run it
I of course installed dependencies 
`sudo apt-get install tesseract-ocr xclip python3-dev python3-tk python3-pil.imagetk libleptonica-dev libtesseract-dev libnotify-bin`

View Bellow

`pip3 install normcap`
Requirement already satisfied: normcap in /usr/local/lib/python3.7/dist-packages (0.1.11)
Requirement already satisfied: pyclip>=0.5.4 in /usr/local/lib/python3.7/dist-packages (from normcap) (0.5.4)
Requirement already satisfied: notify-py>=0.3.1 in /usr/local/lib/python3.7/dist-packages (from normcap) (0.3.2)
Requirement already satisfied: importlib-resources>=5.1.2 in /usr/local/lib/python3.7/dist-packages (from normcap) (5.1.2)
Requirement already satisfied: Pillow>=8.2.0 in /usr/local/lib/python3.7/dist-packages (from normcap) (8.2.0)
Requirement already satisfied: pyscreenshot>=2.3 in /usr/local/lib/python3.7/dist-packages (from normcap) (3.0)
Requirement already satisfied: tesserocr>=2.4.0 in /usr/local/lib/python3.7/dist-packages (from normcap) (2.5.1)
Requirement already satisfied: mss>=6.1.0 in /usr/local/lib/python3.7/dist-packages (from normcap) (6.1.0)
Requirement already satisfied: jeepney; platform_system == "Linux" in /usr/local/lib/python3.7/dist-packages (from notify-py>=0.3.1->normcap) (0.6.0)
Requirement already satisfied: loguru in /usr/local/lib/python3.7/dist-packages (from notify-py>=0.3.1->normcap) (0.5.3)
Requirement already satisfied: zipp>=0.4; python_version < "3.8" in /usr/local/lib/python3.7/dist-packages (from importlib-resources>=5.1.2->normcap) (3.4.1)
Requirement already satisfied: entrypoint2 in /usr/local/lib/python3.7/dist-packages (from pyscreenshot>=2.3->normcap) (0.2.4)
Requirement already satisfied: EasyProcess in /usr/local/lib/python3.7/dist-packages (from pyscreenshot>=2.3->normcap) (0.3)

`normcap`
!strcmp(locale, "C"):Error:Assert failed:in file baseapi.cpp, line 209
Segmentation fault

**Comment by dynobo** [comment]
Hi @liolio6, thanks for reporting the bug!
Do you get additional output, if you execute `normcap --verbose`? And which display manager do you use? Gnome on X11?

**Comment by dynobo** [comment]
@liolio6, could you please upgrade NormCap to the version I just released and report back, if the workaround works for you?
```
pip3 install normcap==0.1.12
```
Thanks!

**Comment by liolio6** [comment]
Hey @dynobo  Its work perfectly 
Really thanks
Your soft is awesome
