### ISSUE TITLE
Error on Ubuntu 16.04, python3.8

### ISSUE THREAD

**Issue by bagustris** [dynobo/normcap#109]
I was able to install and use it on Ubuntu 20.04 using python 3.8, but failed on Ubuntu 16.04, also using python 3.8. Both are installed using pip.

The error says:
`AttributeError: type object 'tesserocr.OEM' has no attribute 'LSTM_ONLY'`

Any idea to resolve?

I checked my tesserocr on python3.8 is version '2.5.1' and update it to version 4.1.1
Now, the following tesseract-ocr is installed in my 16.04 and still resulting the same issue.

```bta@mbp:~$ tesseract --version
tesseract 4.1.1-rc2-25-g9707
 leptonica-1.78.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.6 : zlib 1.2.8 : libwebp 0.4.4 : libopenjp2 2.3.0
 Found AVX
 Found SSE
 Found libarchive 3.1.2
```

**Comment by dynobo** [comment]
Hi @bagustris , thanks for your error report! :-)

Could you please try uninstalling `tesserocr` (the python package, not `tesseract-ocr` the ubuntu package for the OCR backend) and then re-install it without cache?
```python
pip3 uninstall tesserocr
pip3 install --no-cache-dir tesserocr
```
It would be possible, that when tesserocr was installed during the normcap installation it was build against your old `tesseract` version, the commands above might fix that.

In any case I'd be happy to hear how it went. If the problem persists, I'll try installing Ubuntu 16.04 myself to reproduce the issue.

**Comment by bagustris** [comment]
Great answer!
I just did the first command only (uninstall tesserocr) and then install normcap. Now it works like a charm. Yesterday I predicted that  normcap still used old tesserocr that produces that error, but I don't know how to get rid of it. This is my complete commands that work.
```
pip3.8 uninstall tesserocr
pip3.8 install --user normcap
```
Thanks a lot!
