### ISSUE TITLE
Please help testing the new beta version 0.2.0-b1

### ISSUE THREAD

**Issue by dynobo** [dynobo/normcap#110]
I've published a 0.2.0-b1 beta-release, with major changes.

**It would be really great if you could help testing it and provide feedback (positive or negative) here in this ticket**

### Changes

- (Almost) total rewrite of NormCap!
- Switch from Tk to Qt as UI Framework
- Easy to use binary package releases (no hassle with dependencies anymore!)
- Better support for HiDPI
- Better support multi monitor setups (MacOS)
- Better support for Wayland (Linux)
- Experimental system tray support (start with `--tray` )

### How to test

Either [download the binary/installer](https://github.com/dynobo/normcap/releases/tag/v0.2.0-b1) _or_ build from source off the branch [feature/switch-to-qt5](https://github.com/dynobo/normcap/tree/feature/switch-to-qt5).

The updated [README](https://github.com/dynobo/normcap/tree/feature/switch-to-qt5) provides additional information.

**Comment by thecoder-001** [comment]
Seems to be working perfectly on initial testing on both MacOS big sur and Gnome 40. The system tray support seems to be working well too [only tested on gnome for now]. 
The cpu & memory resources being used while idle are also almost non-existent, making the system tray icon worthwhile.

Thanks a lot for the awesome work!

**Comment by thecoder-001** [comment]
Capturing from system tray on macos doesn't seems to be working.
[Drive link](https://drive.google.com/file/d/1FVLOLdv29wQvWeUTomU5DehrhHvKdGdV/view?usp=sharing) to video demonstrating the issue (the video was too large to be directly uploaded to github).

**Comment by dynobo** [comment]
Very valuable feedback, @thecoder-001 ! Thanks, I'll work on a fix.

**Comment by Takrin** [comment]
Hey @dynobo,
I've tested the Windows installer and I noticed two points:
1. The installer does not include the nice icon. You may want to add it there as well.
2. The notification only shows up in tray mode.

Thank you for this great tool!

**Comment by ashishpatel1992** [comment]
Hi @dynobo,
I have tested this and found that:-
1) No Tray Icon even after passing --tray
2) Text capturing is no more working ( I mean application gets launched, Screen can be selected but the text doesn't get copied to clipboard)

**Comment by dynobo** [comment]
Hey @ashishpatel1992, thanks for testing! :-) 
Could you please start the application with the two switches `--tray --very-verbose` from the command line and post the output? That would help be me debugging things...

**Comment by ashishpatel1992** [comment]
I tried running with these two switches but it didn't work. You can see the same here in screenshot. Nothing got pasted. Neither verbose worked. 
 
![test](https://user-images.githubusercontent.com/652311/120115692-8975e600-c1a2-11eb-898a-c33a08ecbc6d.gif)

**Comment by dynobo** [comment]
@ashishpatel1992 : Please try `python.exe -m normcap --tray --very-verbose`. Without the `w` in `python`. 
(`pythonw.exe` is basically a wrapper for python gui applications. It suppresses any outputs.)

**Comment by ashishpatel1992** [comment]
Hi @dynobo ,
I think I am able to make it work now! Found the issue that ` tesserocr` was not installed, May be you can make clear in the README.md, as it was mentioned to follow one of the A) B) or C), Simply installing `normcap_win64_installer.exe` doesnt help.

Also a suggestion, when the app launches and if `tesserocr` is not installed, we can popup a window informing the user to install it with a given provided link.

**Comment by dynobo** [comment]
@ashipatel1992, theoretically, all necessary dependencies (including`tesserocr`) _should_ be included in the msi-installer. Seems like this is not yet the case, so I have to take a look into that. Thanks for identifying this issue! :)

**Comment by dynobo** [comment]
Thanks, everybody, for testing and filing the issues! I (hopefully) was able to fix all of them and published another beta:

[Please help testing the beta version 0.2.0-**b2** by reporting issues to the new thread](https://github.com/dynobo/normcap/issues/114)
