### ISSUE TITLE
[MacOS] Red frame is not visible around menubar

### ISSUE THREAD

**Issue by dynobo** [dynobo/normcap#119]
The main capture window (with the red frame) seems to always stay behind Mac's menubar. This not only looks a bit ugly, it also makes it impossible to capture text on the menubar itself.

**Comment by thecoder-001** [comment]
A similar effect can be observed in Gnome40 too.
Screenshots:
Normal-
![image](https://user-images.githubusercontent.com/25097841/123280265-45b69800-d526-11eb-980b-7d2966b116ce.png) 
During capture mode-
![image](https://user-images.githubusercontent.com/25097841/123280330-51a25a00-d526-11eb-8078-696b676a9201.png)

**Comment by dynobo** [comment]
@thecoder-001  Thanks for the report! Let's track problem on MacOS here in this ticket, and the Gnome problem in #119. While the problem is indeed related, from my experience it is very likely that it has to be solved separately. I don't think there is a configuration that will work well on Gnome _and_ MacOS, but that's also not necessary, as the configuration is chosen conditionally anyway,

For anyone who want to take a look into this [here is the relevant part of the code](https://github.com/dynobo/normcap/blob/main/src/normcap/window_base.py#L204-L272)

**Comment by dynobo** [comment]
PR #134 introduced a partial fix: The border is now drawn around whole screen, incl. dock & menubar. However, menubar & dock are still not selectable areas.

An alternative solution I found makes everything selectable, but won't accept keyboard input (No close via `esc`) and won't show the cross hair cursor.

Not sure, what's better. Please provide your opinion... :)

**Comment by dynobo** [comment]
This issue was addressed in the latest pre-release `NormCap v0.3.0-beta`. 
Would you mind [help testing `v0.3.0-beta`](https://github.com/dynobo/normcap/discussions/178) and report back, if it solves this issue? Thanks!

**Comment by dynobo** [comment]
Fix confirmed for v0.3.0+
