### ISSUE TITLE
appimage error

### ISSUE THREAD

**Issue by vinniec** [dynobo/normcap#131]
I'm trying the appimage but trying it to lang I get this error:
./NormCap-Linux.AppImage 
/tmp/.mount_NormCasYMHFZ/AppRun: riga 7:  9375 Annullato               $APPDIR/usr/bin/python3 -s -m normcap "$@"

**Comment by dynobo** [comment]
Hi @vinniec, thanks for your bug report!

Can you please provide some additional infos:
- Linux distribution & version
- Display Manager (KDE, Gnome, XFCE,...)
- Output when you run `./NormCap-Linux.AppImage --very-verbose`

Thanks!

**Comment by vinniec** [comment]
kali-rolling 2020.2
xfce 4.14
```
01:40:14 - INFO    - normcap.app            - L:38  - Starting Normcap v0.2.4
01:40:14 - DEBUG   - normcap.app            - L:39  - CLI command: /tmp/.mount_NormCaUc58YT/usr/app/normcap/__main__.py --very-verbose
01:40:14 - DEBUG   - normcap.app            - L:42  - QT LibraryPaths: ['/tmp/.mount_NormCaUc58YT/usr/app_packages/PySide2/Qt/plugins']
01:40:14 - DEBUG   - normcap.utils          - L:205 - [QT] L:0, func: None, file: None
01:40:14 - DEBUG   - normcap.utils          - L:206 - [QT] QtInfoMsg - Could not load the Qt platform plugin "xcb" in "" even though it was found.
01:40:14 - DEBUG   - normcap.utils          - L:205 - [QT] L:0, func: None, file: None
01:40:14 - DEBUG   - normcap.utils          - L:206 - [QT] QtFatalMsg - This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

/tmp/.mount_NormCaUc58YT/AppRun: riga 7: 20422 Annullato               $APPDIR/usr/bin/python3 -s -m normcap "$@"
```

Thanks for the reply :)

**Comment by dynobo** [comment]
Interesting bug. 

I tried to reproduce it with [Kali VirtualBox Image](https://www.kali.org/get-kali/#kali-virtual-machines), but here the AppImage works without any issues.

Could you please check if you have the following two packages installed:
```
$ apt list | grep -E 'libqt5x11|libxcb-xiner'

libqt5x11extras5-dev/kali-rolling 5.15.2-2 amd64
libqt5x11extras5/kali-rolling,now 5.15.2-2 amd64 [installed,automatic]
libxcb-xinerama0-dev/kali-rolling 1.14-3 amd64
libxcb-xinerama0/kali-rolling,now 1.14-3 amd64 [installed,automatic]
```
If one of them is missing, please try installing them.

If this does not solve the issue, please try running NormCap also with the qt debug environment variable and report it's output:
```
$ QT_DEBUG_PLUGINS=1 ./NormCap-Linux.AppImage --very-verbose
```

Thanks for collaborating on this! :-)

**Comment by vinniec** [comment]
Work flawlessly! the missing package was libxcb-util1! Thanks for the help!
I have another wounder, it possible to use it as a library in python to automatically capture a portion of the screen isntead to select by hand?

**Comment by dynobo** [comment]
Good to know! I'll add an info text that asks the user to install `libxcb-util1` in case of that error occurres. :-)

The idea about separating the ocr-parts into a separate library is nice an definitely helpful. I'll add in on my backlog: #133

However, this is currently not high prio, so you might want to take a look at [screen-ocr](https://github.com/wolfmanstout/screen-ocr) or [textshot](https://github.com/ianzhao05/textshot). Depending on your needs, the basic functionality is [quite easy to implement](https://stackabuse.com/pytesseract-simple-python-optical-character-recognition). It gets a lot more complicated once you'd like to support different systems and stuff like multiple monitors or HIDPI.
