### ISSUE TITLE
[ERROR] Not launching in Fedora 35 Wayland

### ISSUE THREAD

**Issue by nesper8** [dynobo/normcap#153]
Log: 
```
19:12:31 - INFO - normcap.normcap - Starting NormCap v0.1.13 ...
Traceback (most recent call last):
  File "/home/nep/.local/bin/normcap", line 8, in <module>
    sys.exit(run())
  File "/home/nep/.local/lib/python3.10/site-packages/normcap/__main__.py", line 5, in run
    _ = main()
  File "/home/nep/.local/lib/python3.10/site-packages/normcap/normcap.py", line 171, in main
    normcap_data = client_code(capture, normcap_data)
  File "/home/nep/.local/lib/python3.10/site-packages/normcap/normcap.py", line 122, in client_code
    result = handler.handle(normcap_data)
  File "/home/nep/.local/lib/python3.10/site-packages/normcap/handlers/capture_handler.py", line 44, in handle
    request = self._take_screenshot_alternative(request)
  File "/home/nep/.local/lib/python3.10/site-packages/normcap/handlers/capture_handler.py", line 101, in _take_screenshot_alternative
    img_complete = ImageGrab.grab(backend="gnome-screenshot")
  File "/home/nep/.local/lib/python3.10/site-packages/pyscreenshot/__init__.py", line 30, in grab
    return backend_grab(backend, bbox, childprocess)
  File "/home/nep/.local/lib/python3.10/site-packages/pyscreenshot/loader.py", line 156, in backend_grab
    return force(backend, bbox, childprocess)
  File "/home/nep/.local/lib/python3.10/site-packages/pyscreenshot/loader.py", line 150, in force
    im = obj.grab(bbox)
  File "/home/nep/.local/lib/python3.10/site-packages/pyscreenshot/plugins/gnome_screenshot.py", line 27, in grab
    im = read_prog_img([PROGRAM, "-f"])
  File "/home/nep/.local/lib/python3.10/site-packages/pyscreenshot/tempexport.py", line 27, in read_prog_img
    im = read_func_img(run_prog)
  File "/home/nep/.local/lib/python3.10/site-packages/pyscreenshot/tempexport.py", line 15, in read_func_img
    func(filename, bbox)
  File "/home/nep/.local/lib/python3.10/site-packages/pyscreenshot/tempexport.py", line 25, in run_prog
    raise RunProgError(p.stderr)
pyscreenshot.tempexport.RunProgError: ** Message: 19:12:31.876: Unable to use GNOME Shell's builtin screenshot interface, resorting to fallback X11.

(gnome-screenshot:15494): Gdk-CRITICAL **: 19:12:31.876: gdk_pixbuf_get_from_surface: assertion 'width > 0 && height > 0' failed

(gnome-screenshot:15494): GdkPixbuf-CRITICAL **: 19:12:31.876: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(gnome-screenshot:15494): GdkPixbuf-CRITICAL **: 19:12:31.876: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug


(gnome-screenshot:15494): GdkPixbuf-CRITICAL **: 19:12:31.876: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(gnome-screenshot:15494): GdkPixbuf-CRITICAL **: 19:12:31.876: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(gnome-screenshot:15494): Gtk-CRITICAL **: 19:12:31.906: gtk_window_resize: assertion 'width > 0' failed

** (gnome-screenshot:15494): CRITICAL **: 19:12:31.906: Unable to capture a screenshot of any window
```

**Comment by dynobo** [comment]
Thanks for reporting this issue!
Which Desktop Environment are you using? Gnome Shell? If yes, which version? `Thanks for reporting this issue!
Which Desktop Environment are you using? Gnome Shell? If yes, which version? `Thanks for reporting this issue!
Which Desktop Environment are you using? Gnome Shell? If yes, which version? `gnome-shell --version`

**Comment by dynobo** [comment]
Oh, take a second look, I've noticed that you are using the very old version `v0.1.13`. 
Can please update and try again? (Or do you have a reason why you are using that old one?)

**Comment by nesper8** [comment]
GNOME Shell 41.1

Im using the pip version actually which is not upgrade after `pip install --upgrade normcap`

**Comment by nesper8** [comment]
This comes on the latest AppImage
```
Traceback (most recent call last):
  File "/tmp/.mount_NormCaT2VKlT/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/tmp/.mount_NormCaT2VKlT/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/.mount_NormCaT2VKlT/usr/app/normcap/__main__.py", line 3, in <module>
    from normcap.app import main
  File "/tmp/.mount_NormCaT2VKlT/usr/app/normcap/app.py", line 20, in <module>
    from PySide2 import QtCore, QtNetwork, QtWidgets
ImportError: /tmp/.mount_NormCaT2VKlT/usr/lib/python3.7/lib-dynload/../../libcrypto.so.1.1: version `OPENSSL_1_1_1b' not found (required by /lib64/libk5crypto.so.3)
```

**Comment by dynobo** [comment]
Hey @nesper8, I identified the root-cause. As other users are affected, I decided to track the issue in #159.
Please follow that issue to get informed about updates.

**Comment by dynobo** [comment]
@nesper8 The error you see in AppImage is a different one. It seems like some dependencies are not getting properly packed. Looking into that one, too.

**Comment by dynobo** [comment]
@nesper8, I just released the [v0.2.10](https://github.com/dynobo/normcap/releases/tag/v0.2.10), it should fix the [your first error](https://github.com/dynobo/normcap/issues/153#issue-1054898612), but it doesn't yet solve [the appimage dependency issue](https://github.com/dynobo/normcap/issues/153#issuecomment-972732539).

However, as the Python package shouldn't have any dependency issue (because you have to install the deps on your own ;) it would be awesome if you could test the [v0.2.10 from pypi.org](https://pypi.org/project/normcap/) and report back how it works for you :-)

**Comment by nesper8** [comment]
I... uh switched to windows so really cant test it out

**Comment by nesper8** [comment]
back on fedora again
pip version works pretty well

would love to see if it would remove the dependancy for xclip sometime in the future

**Comment by dynobo** [comment]
@nesper8 Oh, if I remember correctly `xclip` actually shouldn't be a dependency anymore. It was dropped as dependency quit some time ago... Did I miss it somewhere in the documentation?

**Comment by nesper8** [comment]
yeah looks like i have an older version 0.1.13 spcifically due to python3.10+

**Comment by dynobo** [comment]
Thx for trying and reporting back, @nesper8 ! :blush:

Yes, I couldn't solve the openssl issue in the appimage (yet).

No need to uninstall your system's Python version in order to use a different version: It is quite common to install different versions in parallel, afaik [`pyenv`](https://github.com/pyenv/pyenv) is the most popular tool for that.

However, if you are not familiar with `pyenv`, I'd recommend you just keep using the (older) `NormCap` version if that works for you. You can still switch to a new version, once the openssl issue is solved or I was able to make it ready for Python 3.10. :-)

**Comment by nesper8** [comment]
no worries mate
after rigorous testing i finally got the latest version working through the magic of shell scripts
