### ISSUE TITLE
Does not work on wayland (plasma)

### ISSUE THREAD

**Issue by Shaurya-Kalia** [dynobo/normcap#155]
On using on wayland, screen becomes grey with ability to select area. Choosing a random area does nothing though
![Screenshot_20211206_181619](https://user-images.githubusercontent.com/6441797/144848524-752f82f2-5565-4d70-ba86-5ced9a513ffe.png)

**Comment by dynobo** [comment]
Hi @Shaurya-Kalia, 

NormCap on Plasma requires window transparency to be set on. It [seems like](https://forum.manjaro.org/t/cant-enable-blur-transparency-effect/25229/2) that depends on the compositor as well as the used theme. Could you please check if this is the case for your distro as well? 

If that's not the case, please provide the name and version of your distro, plus the name of the plasma theme you are using. Then I could try to replicate it. 

PS: #126 was a similar issue

**Comment by Shaurya-Kalia** [comment]
Okay, i forced it with kwin compositor to have less opacity, but it does not seem to work. On running with terminal, it gives the following error on selecting any area 
`15:02:49 - WARNING - normcap.main_window    - L:285 - Area of 0 too small. Skip OCR`

**Comment by dynobo** [comment]
@Shaurya-Kalia, Just FYI: I'm exploring an alternative way display method for NormCap, where instead of showing a transparent window as an overlay, I show a normal window but with a screenshot of the desktop as background image. (Many screenshot tools are doing it like this, especially if they have to work cross platform). If that turns our to work, it won't require window transparency anymore and should also fix your issue. I'll keep you updated.

**Comment by dynobo** [comment]
Hi @Shaurya-Kalia , this issue was addressed in the latest pre-release `NormCap v0.3.0-beta`. 
Would you mind [help testing `v0.3.0-beta`](https://github.com/dynobo/normcap/discussions/178) and report back, if it solves this issue? Thanks!

**Comment by Shaurya-Kalia** [comment]
> Hi @Shaurya-Kalia , this issue was addressed in the latest pre-release `NormCap v0.3.0-beta`. Would you mind [help testing `v0.3.0-beta`](https://github.com/dynobo/normcap/discussions/178) and report back, if it solves this issue? Thanks!

Built normcap unstable from source. Get the following error on selecting a region:
`01:54:51 - ERROR   - normcap.utils          - L:104 - Uncaught exception! Quitting NormCap!
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/normcap/gui/main_window.py", line 275, in _grab_image
    self.capture = grab_screen(capture=self.capture)
  File "/usr/lib/python3.10/site-packages/normcap/screengrab.py", line 92, in __call__
    if system_info.gnome_shell_version() < parse_version("41"):
TypeError: '<' not supported between instances of 'str' and 'Version'
01:54:51 - ERROR   - normcap.utils          - L:107 - Please open an issue with the output above on https://github.com/dynobo/normcap/issues`

**Comment by dynobo** [comment]
@Shaurya-Kalia: Thanks for trying to help! Did you use the code-base from the [dev](https://github.com/dynobo/normcap/tree/dev)-branch? (The file `screengrab.py` in the error got renamed some time ago, and shouldn't be existing in the v0.3.0-beta)

PS: I got myself confused by my uncommon beta-release strategy... :see_no_evil: 
Will try to do this better next time...

**Comment by Shaurya-Kalia** [comment]
I guess i used the unstable release in main branch. I will try with unstable release of dev branch then

**Comment by dynobo** [comment]
Thanks, @Shaurya-Kalia. Sorry for the confusion, it seems like I messed up the "Release": The source tar balls actually contain the main branch, but it was build from dev branch... If you just checkout/download the latest version on `dev`, that's best, I guess.

**Comment by dynobo** [comment]
This issue should not occur anymore, as recent versions of NormCap do not depend on transparency anymore. 

Please re-open, in case it persists nevertheless.

**Comment by Shaurya-Kalia** [comment]
Yes, normcap works as expected on plasma-wayland now
