### ISSUE TITLE
Doesn't detect well line break

### ISSUE THREAD

**Issue by jechaviz** [dynobo/normcap#156]
If I try to capture a snippet of code, after ; always shrinks the line break. Just try with any java code.

**Comment by dynobo** [comment]
Thanks for reporting this issue, @jechaviz. 
Indeed, handling line breaks (and white space in general) is quite rudimentary, at the moment. 

By default, NormCap runs in "parse" mode, where it applies some heuristics to guess, if a line break in the text should be removed (which is most often useful, if you just want to capture a paragraph of text). But the "parse" mode breaks totally, when you try to capture programming code (see  ["Capture modes"](https://dynobo.github.io/normcap/#usage) for details). Implementing heuristics to detect and format code correctly [is on my roadmap](https://github.com/dynobo/normcap/issues/29), but it's quite complicated and not very high priority for me.

What you can do in the meanwhile is to set NormCap to "raw" mode, which should at least preserve the line breaks. However, indentation is probably not captured very well and you shouldn't expect top recognition performance, either, as `tesseract` is trained on natural language (grammar, syntax), which do not apply to programming languages. Using the tesseract language `osd` or `equ` (see [here](https://tesseract-ocr.github.io/tessdoc/Data-Files#special-data-files)) might improve this a bit.

Does this help you for now?

**Comment by jechaviz** [comment]
Yes it helps. Thank you. You can close this ticket, and I'll wait your update.
