### ISSUE TITLE
Error under manjaro 21.2.2 - might be similar to #155

### ISSUE THREAD

**Issue by tobiastesteron** [dynobo/normcap#184]
Installed from AUR normcap 0.2.10-1 

The following appears when run in Konsole with -v:
normcap -v                                                                                                                                                                                           ✔ 
15:35:30 - INFO    - normcap.app            - L:41  - Start NormCap v0.2.10
15:35:30 - INFO    - normcap.utils          - L:148 - Copy 0 traineddata files to config directory
15:35:59 - INFO    - normcap.main_window    - L:272 - Take screenshot of position (1501, 2372, 2420, 3087)
15:35:59 - INFO    - normcap.enhance        - L:17  - Apply enhancements to image
15:36:01 - ERROR   - normcap.utils          - L:104 - Uncaught exception! Quitting NormCap!
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/normcap/gui/main_window.py", line 291, in _capture_to_ocr
    self.capture = perform_ocr(
  File "/usr/lib/python3.10/site-packages/normcap/ocr.py", line 63, in __call__
    capture = self.extract(capture)
  File "/usr/lib/python3.10/site-packages/normcap/ocr.py", line 82, in extract
    words = self.tsv_to_list_of_dicts(tsv_data)
  File "/usr/lib/python3.10/site-packages/normcap/ocr.py", line 162, in tsv_to_list_of_dicts
    words[idx][key] = int(value)  # type: ignore # (casting on purpose)
ValueError: invalid literal for int() with base 10: '90,876602'
15:36:01 - ERROR   - normcap.utils          - L:107 - Please open an issue with the output above on https://github.com/dynobo/normcap/issues

Thanks for your help and thanks for your application !

**Comment by dynobo** [comment]
Hi @tobiastesteron, thanks for reporting the issue. Actually, you are not the first one with that problem, please take a look at #170, especially at [my latest comment there](https://github.com/dynobo/normcap/issues/170#issuecomment-1050242203).

I'm closing this ticket as duplicate for now, if it turns out that your problem is something different, please feel free to reopen.
