### ISSUE TITLE
delayed screen capture and no notifications in versions newer than 0.3.0 (Windows)

### ISSUE THREAD

**Issue by schnednet** [dynobo/normcap#218]
I just updated to the latest version normcap-0.3.4 after a Windows 10 reinstall. In this version, the screen capture function is heavily delayed for me (a few seconds) and no Windows notification appears anymore after successful text recognition.

A downgrade to 0.3.0 fixed the problem. But I had to remove some registry keys manually to reinstall an older version.

Thanks a lot for your work. I enjoy normcap.

**Comment by museHD** [comment]
Same problem here. Updated to 0.3.4 and screen freezes with the red border until I click somewhere else on the screen, or after 4-5 seconds have passed.

**Comment by museHD** [comment]
Ahh. Thanks @dynobo, that makes sense.
Could you provide an example of this notification? I don't see any notification pop up. 

Also how do I check whether I have notifications enabled? Do you mean Windows notifs or is it a Normcap thing?

**Comment by dynobo** [comment]
@museHD, NormCap triggers a notification in Windows' native notification system. But the bug prevents you from seeing it, because when the NormCap-window hides, the notification disappears, too.

As a workaround until the next version, you can try to disable the notification through NormCaps settings menu:
![screenshot](https://user-images.githubusercontent.com/11071876/177878099-9ca88423-7067-4e02-9275-8ef42ca1d284.png)

**Comment by schnednet** [comment]
hi dynobo, notifications are enabled in normcaps for me. But your workaround with deactivating them works. Thank you very much. I am looking forward to the new version :)

**Comment by eclipseo** [comment]
How do you get the tray? I don't have a tray or GUI, just the icon in my start menu or taskbar?
Sorry if I derail, but it might be related.

**Comment by dynobo** [comment]
@eclipseo , once you start NormCap, you should see a red border around your screen and a red cog wheel in the top right, which opens the settings menu where you can enable the tray (see picture above). 

If you don't see that cog wheel, please open a new issue with information about your operating system. Thanks!

**Comment by dynobo** [comment]
@eclipseo,  @schnednet, @museHD, the issue should be fixed with the [v0.3.5 release](https://github.com/dynobo/normcap/releases/tag/v0.3.5) I just published. Could you please try and report your result?

**Comment by schnednet** [comment]
@dynobo Yes, the problem is now also solved for me in the new version. Text recognition works immediately and I also see notifications again. Many thanks for the effort.

**Comment by dynobo** [comment]
Thanks for the feedback!
