### ISSUE TITLE
[macOS] Can not take screenshot - show empty desktops

### ISSUE THREAD

**Issue by deepblue81** [dynobo/normcap#219]
Hello, I only know that the previous versions have always worked, since the last update, the recording of screenshots no longer works. I open NormCap and go in the menu bar above to activate the screenshot function, immediately at the same time by Mission Control a new empty desktop is created and it is still quickly displayed in my previous desktop - where I have all programs open - a system message where I am asked if I allow NormCap to capture the screen, which I have to confirm in under Security&Privacy > Screen Capture. But I have this setting active since the 1st application of NormCap, the hook is always in - but it always asks me every time I start NormCap. Then I can take in any case no screenshot of my text, because I landed in an empty desktop and when I switch back to my main desktop NormCap is no longer active! 
Is there any way to solve this problem? Thanks...

MacOS 12.4, NormCap 0.3.4

<img width="1366" alt="Bildschirmfoto 2022-06-27 um 09 39 06" src="https://user-images.githubusercontent.com/108260618/175887931-482686d4-f2d3-47be-a0f6-e2df759b7010.png">

**Comment by dynobo** [comment]
Hi @deepblue81 , thanks a lot for reporting this issue! 

Do you remember the version number of the last NormCap version that worked for you?

**Comment by dynobo** [comment]
Just FYI: I experienced a similar (or the same?) issue while testing the new [NormCap v0.3.5](https://github.com/dynobo/normcap/releases/tag/v0.3.5), seeing only an empty desktop after NormCap start. 

This is definitely an issue with the Screen Capture permissions, which doesn't work correctly, _despite_ the hook showing as active in "Security & Privacy".

My best guess so far: MacOS creates the entry for NormCap in "Security & Privacy" > "Screen Capture", but when installing the _next_ version of NormCap, this new version is somehow not mapped correctly with the permissions of the previous version... 
 
Two workarounds you could try:
1. Remove the permissions for "Screen Capture" in "Security & Privacy"; Close the settings, then re-add the permission. (Basically un-tick, make sure it's store, and re-tick the checkbox)
2. If that doesn't work, uninstall NormCap completely  (should also remove all permissions) before installing the new version.

Obviously, this is it not how it _should_ be. If anyone has more ideas about the possible underlying issue and how to solve it, that would be great!
