### ISSUE TITLE
[flatpak] Error "Invalid dbus interface"

### ISSUE THREAD

**Issue by dynobo** [dynobo/normcap#224]
Reported by @pizzadude:
> Hi, I found this program on flathub. The flatpak doesn't work for me in KDE wayland, when capturing I get an error "22:36:44 - ERROR - normcap.gui.utils:153 - Invalid dbus interface". I use KDE version 5.25.3 on Fedora Linux if that helps.
>
>The AppImage works fine for me in KDE wayland though.

**Comment by dynobo** [comment]
@pizzadude, I can't reproduce this on Fedora 36, KDE 5.25.3, wayland. Could you please try it from the command line with the debug flag and post the output?:
```sh
flatpak run com.github.dynobo.normcap -v debug
```

**Comment by pizzadude** [comment]
Nevermind, I still do get the error, but the flatpak works. I must have misinterpreted how the app worked when I first used the flatpak, because the app quits after you take the screenshot.

I'm sorry if I wasted your time.

One thing that is unrelated is that on KDE wayland, when you take a screenshot, it puts a full screen image in ~/Pictures/

**Comment by dynobo** [comment]
Ah, I see, there is this error in the console! This is a bit misleading, I'll reduce the level to a warning or something.
Totally understable, by the way, that you didn't get right away how NormCap works. I think this is also due to the lack of information on the flathub-page, which will be addressed in #226.

About the image file being stored in ~/Pictures/: 
Unfortunately, this is the standard behavior, if third party apps query a screenshot on Wayland. Other screenshot-tools, like FlameShot etc, show the same behavior. I _could_ try to detect and delete this image, but it doesn't feel right to me to mess around within the users' files. The best solution, if Wayland's screenshot-API would provide an option for that, but I don't know if something like that is planned.
