### ISSUE TITLE
Integrate flatpak building into CI/CD

### ISSUE THREAD

**Issue by dynobo** [dynobo/normcap#225]
On tagging a new release in the NormCap repo, the new version should also be published as flatpak.

To do this, the [repo with the flatpak manifest](https://github.com/flathub/com.github.dynobo.normcap) need to be cloned, updated and pushed, I guess?

**Comment by Tim453** [comment]
There is a [tool](https://github.com/flathub/flatpak-external-data-checker#pypi-checker), which can automatically check for new releases/tags and create the corresponding pull requests.

**Comment by dynobo** [comment]
@Tim453 Looks promising, thanks!

**Comment by dynobo** [comment]
Implemented for the PyPi packages with flathub/com.github.dynobo.normcap#1 using the mechanism @Tim453 suggested. For the tesseract related binaries, it's probably wise to not bump those automatically, as they might break stuff.
