### ISSUE TITLE
[FlatPak] How to add additional languages to NormCap?

### ISSUE THREAD

**Issue by idanka** [dynobo/normcap#239]
i use ubuntu and install flatpak - NormCap
where do we copy the language file?

**Comment by dynobo** [comment]
It's not yet possible, I didn't have on my radar, that within flatpak this must be handled differently...
It is definitely high prio for me, subscribe to this issue for updates!
 
Thanks for reporting, @idanka!

**Comment by dynobo** [comment]
Could you please try the latest NormCap v0.3.10 flatpak? You now should be able to [add additional languages](https://dynobo.github.io/normcap/#faqs-languages) there.

**Comment by dynobo** [comment]
Closing, as this should be fixed since v0.3.10.
