### ISSUE TITLE
Add notifcation/splash screen to show whats happenig after screenshot selection

### ISSUE THREAD

**Issue by dynobo** [dynobo/normcap#27]
E.g.:
- "Detecting text..." -> "Parsing email.." -> "Trigger action..."
- Preferably icons only, no text

**Comment by ashishpatel1992** [comment]
Hi @dynobo 
I have worked on a feature that pushes a notification on `Windows` that text is copied to clipboard
Here is sample notification. Although I would like you to suggest me the title.
(In this example for the title I have chosen to display  `noarmcap - Text Captured`
below that, I have shown part of the text copied in a single line and also handled the case when no text is detected)
![image](https://user-images.githubusercontent.com/652311/97783911-e1268180-1bc0-11eb-970b-629e69b7e1ea.png)

When no text is present to be copied

![image](https://user-images.githubusercontent.com/652311/97783930-fdc2b980-1bc0-11eb-9c8d-1b24567e17b5.png)


I think it really looks nice informing that content is copied to their clipboard.
So I have two ideas for the copied text in the notification:
1) Show the partial copied text
2) Inform the user top use CTRL+V to paste the text

![image](https://user-images.githubusercontent.com/652311/97783977-467a7280-1bc1-11eb-8cd2-16fa80b4dc0f.png)


Let me know your thoughts on this. If the text seems fine to you I can send you a merge request.

**Comment by ashishpatel1992** [comment]
Hi,
The current notification displayed is having the wrong application name `Python Application (notify.py)`
![image](https://user-images.githubusercontent.com/652311/97823617-964f5b80-1cdf-11eb-99e7-51c5dbd4733d.png)

I am sending you a merge request with `application name` and `version`.

![image](https://user-images.githubusercontent.com/652311/97823681-b717b100-1cdf-11eb-9be9-4aeacff81fce.png)

**Comment by dynobo** [comment]
Thanks, @ashishpatel1992 !

One question: I'm hesitating to publish 0.1.6 as release, because I discovered an issue with the notification on Windows: Shortly before the notification appears, the Powershell-Windows pops up for a very short moment. But this happens only for the compiled .exe build, not when running as Python package. 
Do you experience the same issue? (Execute `python build.py` to generate the .exe, then execute *dist*/normcap-v0.1.6.exe)

I think it's an upstream issue with [notify-py](https://github.com/ms7m/notify-py) which leverages a powershell command under the hood. I'm already investigating...

**Comment by ashishpatel1992** [comment]
Hi @dynobo ,
I haven't reached till that step yet. Stuck with the binary generated.
Although successfully able to compile it. Log here: https://pastebin.com/MHXsQ7RY
The compiled binary was giving me the error:
![image](https://user-images.githubusercontent.com/652311/97847689-04af1080-1d16-11eb-9005-3642017b03da.png)

So, I have manually placed python38.dll to rectify the issue.
But now there is another error `pyi_rth__tkinter` 
![image](https://user-images.githubusercontent.com/652311/97850910-a89abb00-1d1a-11eb-9dae-7c157cbbc8a8.png)

I am not sure how I can fix this. Do you have any idea about this?

**Comment by dynobo** [comment]
Hi @ashishpatel1992,
I your python version 3.8? I think pyinstaller doesn't yet support this... Could you try with 3.7.x?

In the meanwhile I filed an PR for the notification Package: ms7m/notify-py#18
We'll see if/when it get's accepted :-)

**Comment by dynobo** [comment]
Solve with [release v0.1.6](https://github.com/dynobo/normcap/releases/tag/v0.1.6).
Thanks for you input, @ashishpatel1992 !

**Comment by ashishpatel1992** [comment]
Glad to know that issue is fixed. 🥇
