### ISSUE TITLE
[Windows] Microsoft Defender SmartScreen prevented an unrecognized app from starting

### ISSUE THREAD

**Issue by Lonniebiz** [dynobo/normcap#272]
Does anyone know why Window 10 gives such a strong warning upon trying to Install NormCap?
![2022-09-15_13-45](https://user-images.githubusercontent.com/151919/190517987-78eb50ac-9d07-48eb-927e-ad779fa3332d.png)

Typically when I install something, Windows 10 just asks me if I give permission and then I click "ok". This warning is more severe than the other one, and this is why I'm more concerned than usual.

Maybe this is just the new way Window 10 warns about installing applications, but I don't recall encountering this warning before.

**Comment by Lonniebiz** [comment]
`
"You may see this warning message Microsoft Defender SmartScreen prevented an unrecognized app from starting if the antivirus software does not have the files signatures stored in its data bank. This can happen if a program executable file is new to [Windows SmartScreen](https://www.thewindowsclub.com/windows-smartscreen-filter-warnings) or if it has not been so commonly downloaded or used."`
**source:** https://www.thewindowsclub.com/microsoft-defender-smartscreen-prevented-an-unrecognized-app-from-starting

So, maybe it is due to the fact that NormCap is just not yet as popular as is should be.

**Comment by dynobo** [comment]
Hi @Lonniebiz, thanks for reporting this, I wasn't aware of this warning before.

I did a bit of research, and it seems like your guess is correct: The warning shows up, if the application doesn't have enough "reputation", which seems to be an obscure metric somehow calculated by Microsoft.

I think [this answer on SO](https://stackoverflow.com/a/66582477) sums up the options to get rid of the warning quite well. 

Option 2) and 3) involves buying a certificate from Microsoft, which I'm not willing to do.

Option 1), uploading the binary to Microsoft for malware Analysis, seems to be the most promising way, however, at a first quick glance, I couldn't find a way to do this programmatically. 

I don't want to spend time looking deeper into this at the moment, but if someone else could figure out a way how this [submission for malware analysis](https://www.microsoft.com/en-us/wdsi/filesubmission) can be automated and put into [CI/CD right after the build-step](https://github.com/dynobo/normcap/blob/main/.github/workflows/python.yaml#L195-L197), I'd be happy to integrate that.

**Comment by Lonniebiz** [comment]
@dynobo I don't blame you one bit. I wouldn't want to spend much time on something like this either.

Hopefully, someone can do an internet search and find this issue to gain the confidence they need, in the event that they too were alarmed by this "more severe than typical" warning, like I was.

I use NormCap on Linux, but I'm beginning to recommend it to all my Window's friends now that I'm aware it is cross-platform.

**Comment by dynobo** [comment]
Good news: NormCap can now be installed vie [Microsoft App Store](https://apps.microsoft.com/store/detail/normcap/XPDLJNB4B6C2ZR?hl=en-us&gl=us). This version won't trigger Defender SmartScreen.
