### ISSUE TITLE
[Windows 7] missing api-ms-win-core-path-l1-1-0.dll

### ISSUE THREAD

**Issue by harryray33** [dynobo/normcap#275]
Does Normcap run on Win 7?

I'm getting a error...program can't start api-ms-win-core-path-l1-1-0.dll is missing.

**Comment by dynobo** [comment]
Hi @harryray33 , thanks for reporting this issue. Did you get the `.msi`-installer or the did you install the Python package?

**Comment by harryray33** [comment]
Thanks, It's the .msi installer.

I don't have api-ms-win-core-path-l1-1-0.dll anywhere on my computer.

**Comment by dynobo** [comment]
There are quite some [potential causes for this file missing](https://answers.microsoft.com/en-us/windows/forum/all/api-ms-win-core-path-l1-1-1ddl-is-missing/b7afd65f-b4f6-4868-8433-587a543532e5).

As Microsoft's support for Windows 7 ended more than 2(!) years ago, it's also possible, that the installer is just not compatible with it.

You could try to install the Python package instead, but it is more difficult, you need a Python distribution on your system, and then perform [additional steps to install NormCap](https://dynobo.github.io/normcap/#python-package-install-on-windows).

Unfortunately, I don't have such an old Windows version around, so probably I'm not of a big help.

**In case someone with a *supported* Windows version runs into the same issue, please let me know!**

**Comment by harryray33** [comment]
I managed to find the file online, but when I tried to run Normcap I got the following error message.

![App crashed](https://user-images.githubusercontent.com/42322725/192096134-4f3190d5-e2f0-47b9-bcc9-9d7c5d3397b4.JPG)

**Comment by dynobo** [comment]
@harryray33, seems like the pre-build NormCap doesn't work on the good old Windows 7. Please try to install NormCap as Python package instead.

**Comment by GeniusBroccoli** [comment]
Same here, Qt 6 doesn't support Win7...

**Comment by dynobo** [comment]
Thanks for confirmation, @GeniusBroccoli !

I'm going to close this for now as I won't be able to ensure support of deprecated Operating System versions. Feel free to re-open, if you experience this issue on newer Windows versions.
