### ISSUE TITLE
Add possibility to re-capture via hotkey when NormCap is running in tray

### ISSUE THREAD

**Issue by dynobo** [dynobo/normcap#306]
## Problem description

Right now, the only options to repeatedly perform captures are:
1. Configure your system to [start NormCap via a Hotkey](https://dynobo.github.io/normcap/#faqs-shortcuts) and _deactivate_ NormCap's "Keep in system tray" setting. Then you can repeatedly capture text via that hotkey.
    - :heavy_plus_sign: Keyboard driven 
    - :heavy_minus_sign: Slower, as startup time of NormCap adds up
    - :heavy_minus_sign: It's not always clear, when NormCap is closed completely and ready for a second capture
2. _Activate_ NormCap's "Keep in system tray" setting. Then you can repeatedly capture texts via right-click on the tray  icon and selecting "Capture".
    - :heavy_plus_sign: Faster, as NormCap is already loaded
    - :heavy_minus_sign: Not accessible via keyboard
    - :heavy_minus_sign: One right-click and one left-click needed

The goal of this ticket is to improve the situation by enabling re-capture from tray via a hotkey.

## Solution idea

On most operating system's NormCap can't (and doesn't want to) listen to keyboard input for hotkeys all the time, so one idea to tackle this issue could be to modify NormCap's startup behavior:
- As a very first step when NormCap is executed, check if NormCap is already running in the system tray
- If it is, just trigger a re-capture in this already running instance and immediately quit the second instance.

Pro:
- This would also solve the issue, that currently multiple instances of NormCap can be started (but shouldn't).

Open questions:
- How to communicate with the already running instance? Socket?
- Does this solution work with all kind of packages of NormCap?

## Intermediate Workaround

A quick and easy improvement could be to implement a "Capture on left-click" and "Open menu on right-click" behavior for the system tray. While not perfect, this might be fairly simple to implement and saves the user one right-click.

**Comment by dynobo** [comment]
The intermedia workaround is implemented: On systems supporting left click on tray icon, this will trigger a capture again. 

Leaving this ticket open, as I still plan to implement the prevention of running multiple instances of NormCap to solve the underlying issue.

**Comment by Ruakij** [comment]
Is it possible to auto-start normcap on system start without triggering a capture?

When starting normcap, its quite slow (2-4s) compared to when its already running (1-2s) to capture.

Maybe add an option `--daemon` / `-d` for starting it, independent of the Tray (when tray is enabled and in daemon-mode display tray, otherwise run in background without tray icon)

**Comment by dynobo** [comment]
Great idea, @Ruakij ! I've created #439 to track it. Thanks!

**Comment by dynobo** [comment]
The Singleton was implemented in v0.4.1. It now should be possible to launch NormCap repeatedly: It will not create multiple instances of NormCap anymore, instead it will re-trigger a capture.

Closing.

**Comment by rin67630** [comment]
+1 for the shortcut key requirement.
And thank you for making this great piece of software.
