### ISSUE TITLE
I upgraded to v0.4.0 and now I get strange results!

### ISSUE THREAD

**Issue by dynobo** [dynobo/normcap#372]
If you update an earlier version, it might happen that the selected **language** is **automatically set to `ara`**, which stands for "Arabic" and might result in really strange characters. I'm sorry for that, this is an unintended effect of the introduction of the new Language Manager.

**Re-select the appropriate language (e.g. `eng`) in the setting menu**, and everything should work again.

![image](https://user-images.githubusercontent.com/11071876/215541468-c26e23da-db84-4aa3-b74d-ddc6055f8bc4.png)

**Comment by rwese** [comment]
It seems it has lost the previous configured language.

**Comment by dynobo** [comment]
> It seems it has lost the previous configured language.
Yeah, exactly. :see_no_evil:

**Comment by dynobo** [comment]
Removing the warning, as after 3 month hopefully most users have upgraded.

**Comment by johnblommers** [comment]
This issue should not be closed. 

Here I sit on a PopOS Linux machine and there is simply no red gear in evidence on my system. Normcap sits happily in the top bar  but no preference menu is there. Only Capture and Exit menu items are  present. 

So I'm stuck with  garbage OCR characters.

**Comment by dynobo** [comment]
@johnblommers , thanks for your feedback. I'll re-open it and leave it open for some more months...

To everyone with trouble finding the preference menu: The red cog will is only visible in "capture"-mode, when you also see the red border around the screen.

**Comment by dynobo** [comment]
As with [v0.5.0-beta1](https://github.com/dynobo/normcap/releases) a lot of things have changed, I'm closing this issue for now. Please feel free to open a new one, in case the problem still occurs to you.
