### ISSUE TITLE
"this application failed to start because no qt platform plugin could be initialized"

### ISSUE THREAD

**Issue by mapleroyal** [dynobo/normcap#393]
Same issue as https://aur.archlinux.org/packages/normcap#comment-902639

Freshly installed 0.4.0-1 from AUR.

```
>>> normcap
14:51:04 - ERROR   - normcap:206 - [QT] qtfatalmsg - this application failed to start because no qt platform plugin could be initialized. reinstalling the application may fix this problem.

available platform plugins are: xcb, minimal, linuxfb, vkkhrdisplay, vnc, eglfs, offscreen, minimalegl.

[1]    9507 IOT instruction (core dumped)  normcap
```

**Comment by dynobo** [comment]
Hi @mapleroyal, thanks for reporting the error! 
Could you please check, if you have the system package `qt6-base` installed? If not, please try installing it. 
If you are running on Wayland, you might have to install `qt6-wayland` additionally.

**Comment by mapleroyal** [comment]
> Hi @mapleroyal, thanks for reporting the error! Could you please check, if you have the system package `qt6-base` installed? If not, please try installing it. If you are running on Wayland, you might have to install `qt6-wayland` additionally.

I can do it right now, but you should know I've since started just using the appimage. Will re-downloading the AUR version and trying it again still test what you wanted?

For context, I checked and do have `qt6-base` but had to just now download `qt6-wayland`.

**Comment by dynobo** [comment]
@mapleroyal, yes, it would be great if you could re-download the AUR version after installing `qt6-wayland` and try again. The AppImage works independent and does not affect the AUR version. 

For context: You are already the second one reporting this issue. If installing `qt6-wayland` also fixes your problem, I try to convince the AUR package maintainer to add this dependency, at least as optional. That's why it would help me a lot, if you could try :-)

**Comment by mapleroyal** [comment]
> @mapleroyal, yes, it would be great if you could re-download the AUR version after installing `qt6-wayland` and try again. The AppImage works independent and does not affect the AUR version.
> 
> For context: You are already the second one reporting this issue. If installing `qt6-wayland` also fixes your problem, I try to convince the AUR package maintainer to add this dependency, at least as optional. That's why it would help me a lot, if you could try :-)

Yep, it worked. :)

Thanks for the quick responses, and glad I could help!

**Comment by dynobo** [comment]
Thanks for testing. I'll keep this issue open for now to track following improvements:
- [ ] Update [FAQ entry](https://dynobo.github.io/normcap/#faqs-couldnt-load-xcb) on this topic
- [ ] Propose AUR maintainer to add `qt6-wayland` as (optional) dependency
- [ ] Try to capture the error and propose the package installation in the output
