### ISSUE TITLE
[MacOS] Normcap for ARM64 - Normcap hangs system after capture

### ISSUE THREAD

**Issue by gwynnebaer** [dynobo/normcap#411]
Started happening recently (after 13.12.1 install?).
Tried on 0.40.0 and still happens.

How to reproduce:
Run Normcap
Select text

What should happen:
text is captured (no system hang)

What happens instead:
Beachball (cannot use the mouse but can use the keyboard)
Normcap hangs as "Not Responding"
Sometimes Normcap recovers and quits, sometimes it hangs under force-killed.

Workaround:
Type Command+Tab and the hang is resolved (pulling context from Normcap and it works eventually)

**Comment by dynobo** [comment]
Thanks for reporting this, @gwynnebaer !

Could you please try to run NormCap from the commandline with the `-v debug` flag? It should be:
```sh
/Applications/NormCap.app/Contents/MacOS/NormCap -v debug
```
then use your workaround and exit NormCap. In the commandline you should then see some debug logging output. Could you share that output here in the issue? That would help a lot for solving this issue. Thanks!

**Comment by gwynnebaer** [comment]
[debug.txt](https://github.com/dynobo/normcap/files/11139938/debug.txt)

I see there is some kind of outbound network call (not sure what?) that is hanging now. This was not happening before (I am behind a proxy and cannot change that).

Now that I understand the issue, my workaround was probably just "time for the network call to timeout" and it looked like it worked.

I set a network proxy in the Bash shell, re-ran the debug version, and now it works with or without the proxy. Maybe it needed to get out for something, now it doesn't anymore? What is it trying to do going outbound and can I have it honor my proxy settings automatically?

**Comment by dynobo** [comment]
Hi @gwynnebaer , thanks for the log, it helps me a lot! Also I'm glad you found a workaround that works for you.

The network call was triggered by the update check right after NormCap started, as you can see here:
```
DEBUG   - normcap.gui.update_check:132 - Search for new version on https://github.com/dynobo/normcap/releases.atom
2023-04-03 08:30:54.402 NormCap[63387:2987472] 08:30:54 - DEBUG   - normcap.gui.downloader:53 - Download https://github.com/dynobo/normcap/releases.atom
```

You can turn this feature off through the settings menu (cog wheel in top right of screen). In fact, it should be disabled by _default_ (opt-in).

Nevertheless, a hang like that should never happen, so this is also a bug in the network error handling.

Notes to me:
- [ ] verify that update check defaults to "off"
- [ ]gracefully handle timeouts in the downloader

**Comment by dynobo** [comment]
Should be fixed. Please reopen, in case it still occurs!
