### ISSUE TITLE
[Linux, Wayland] Normcap not copying to clipboard when launched through shortcut

### ISSUE THREAD

**Issue by Shaurya-Kalia** [dynobo/normcap#422]
### What happened?

1. Create a custom shortcut for normcap (in this case, made in Plasma wayland via System Settings > Shortcuts >Add applications and assigning shortcut)
2. Launch normcap via shortcut
3. Text is recognised, appears in notification but not copied to clipboard
4. Launch normcap from terminal
5. Text is recognised, appears in notification and is copied to clipboard

### How did you install NormCap?

AUR (Linux)

### Operating System + Version?

Kernel Version: 6.2.12-1-MANJARO (64-bit); Normcap version 0.4.0

### [Linux only] Display Server (DS) + Desktop environment (DE)?

Operating System: Manjaro Linux  KDE Plasma Version: 5.27.4 KDE Frameworks Version: 5.104.0 Qt Version: 5.15.8 Platform: Wayland

### Debug log output?

```shell
This is debug log while launching through terminal. I have no idea how to record it when launching from shortcut:
01:22:06 - INFO    - normcap:29 - Start NormCap v0.4.0
01:22:06 - DEBUG   - normcap:80 - Set QT_QPA_PLATFORM=wayland
01:22:06 - DEBUG   - normcap.gui.tray:71 - System info:
{'cli_args': '/usr/bin/normcap -v debug', 'is_briefcase_package': False, 'is_flatpak_package': False, 'platform': 'linux', 'pyside6_version': '6.4.3', 'qt_version': '6.4.3', 'qt_library_path': '/usr/lib/qt6/plugins, /usr/bin', 'config_directory': PosixPath('/home/shaurya/.config/normcap'), 'normcap_version': '0.4.0', 'ressources_path': PosixPath('/usr/lib/python3.10/site-packages/normcap/resources'), 'tesseract_path': PosixPath('/usr/bin/tesseract'), 'tessdata_path': None, 'envs': {'TESSDATA_PREFIX': None, 'LD_LIBRARY_PATH': None}, 'desktop_environment': <DesktopEnvironment.KDE: 2>, 'display_manager_is_wayland': True, 'screens': [Screen(is_primary=True, device_pixel_ratio=1.0, rect=Rect(left=0, top=0, right=1920, bottom=1080), index=0, screenshot=None)]}
01:22:07 - DEBUG   - normcap.screengrab:46 - Select capture method DBUS portal
01:22:07 - DEBUG   - normcap.screengrab.dbus_portal:194 - Request screenshot with interactive=False
01:22:07 - DEBUG   - normcap.screengrab.dbus_portal:78 - Request accepted
01:22:07 - DEBUG   - normcap.screengrab.dbus_portal:105 - Parse response
01:22:07 - DEBUG   - normcap.screengrab.utils:26 - Virtual geometry width: 1920
01:22:07 - DEBUG   - normcap.screengrab.utils:27 - Image width: 1920
01:22:07 - DEBUG   - normcap.screengrab.utils:28 - Resize ratio: 1.0
01:22:07 - DEBUG   - normcap.gui.tray:43 - Save debug image as /tmp/normcap/2023-04-25_01-22-07_554859_raw_screen0.png
01:22:07 - DEBUG   - normcap.gui.window:131 - Create window for screen 0
01:22:07 - DEBUG   - normcap.gui.window:193 - Set window of screen 0 to fullscreen
01:22:07 - DEBUG   - normcap.gui.window:184 - Move window 0 to (left=0, top=0, right=1920, bottom=1080)
01:22:18 - DEBUG   - normcap.gui.tray:418 - Hide 1 window
01:22:18 - INFO    - normcap.gui.tray:322 - Crop image to region (316, 70, 833, 81)
01:22:18 - DEBUG   - normcap.gui.tray:43 - Save debug image as /tmp/normcap/2023-04-25_01-22-18_364861_cropped.png
01:22:18 - DEBUG   - normcap.gui.tray:355 - Start OCR
01:22:18 - DEBUG   - normcap.ocr.enhance:54 - Scale image x3.2
01:22:18 - DEBUG   - normcap.ocr.enhance:36 - Pad image by 80px
01:22:18 - DEBUG   - normcap.ocr.enhance:73 - Invert image
01:22:18 - DEBUG   - normcap.ocr.recognize:37 - Run Tesseract on image of size (1814, 195) with args:
TessArgs(path=None, lang='eng', oem=<OEM.DEFAULT: 3>, psm=<PSM.AUTO_OSD: 1>, version='5.3.1')
01:22:18 - DEBUG   - normcap.ocr.recognize:53 - OCR result:
OcrResult(tess_args=TessArgs(path=None, lang='eng', oem=<OEM.DEFAULT: 3>, psm=<PSM.AUTO_OSD: 1>, version='5.3.1'), words=[{'level': 5, 'page_num': 1, 'block_num': 1, 'par_num': 1, 'line_num': 1, 'word_num': 1, 'left': 83, 'top': 80, 'width': 81, 'height': 23, 'conf': 30, 'text': '2€T'}, {'level': 5, 'page_num': 1, 'block_num': 1, 'par_num': 1, 'line_num': 1, 'word_num': 2, 'left': 204, 'top': 80, 'width': 131, 'height': 23, 'conf': 65, 'text': 'LEVEL'}, {'level': 5, 'page_num': 1, 'block_num': 1, 'par_num': 1, 'line_num': 1, 'word_num': 3, 'left': 369, 'top': 80, 'width': 52, 'height': 23, 'conf': 57, 'text': 'OT'}, {'level': 5, 'page_num': 1, 'block_num': 1, 'par_num': 1, 'line_num': 1, 'word_num': 4, 'left': 456, 'top': 80, 'width': 166, 'height': 23, 'conf': 9, 'text': 'deldliL'}, {'level': 5, 'page_num': 1, 'block_num': 1, 'par_num': 1, 'line_num': 1, 'word_num': 5, 'left': 660, 'top': 80, 'width': 80, 'height': 23, 'conf': 63, 'text': 'TOr'}, {'level': 5, 'page_num': 1, 'block_num': 1, 'par_num': 1, 'line_num': 1, 'word_num': 6, 'left': 774, 'top': 80, 'width': 196, 'height': 23, 'conf': 83, 'text': 'consoLe'}, {'level': 5, 'page_num': 1, 'block_num': 1, 'par_num': 1, 'line_num': 1, 'word_num': 7, 'left': 1002, 'top': 80, 'width': 170, 'height': 32, 'conf': 40, 'text': 'outputct'}, {'level': 5, 'page_num': 1, 'block_num': 1, 'par_num': 1, 'line_num': 1, 'word_num': 8, 'left': 1206, 'top': 80, 'width': 247, 'height': 32, 'conf': 14, 'text': '(aerauLrt:'}, {'level': 5, 'page_num': 1, 'block_num': 1, 'par_num': 1, 'line_num': 1, 'word_num': 9, 'left': 1491, 'top': 80, 'width': 227, 'height': 32, 'conf': 0, 'text': 'warnwng)'}], image=<PIL.Image.Image image mode=RGB size=1814x195 at 0x7F939B5FF580>, magic_scores={}, parsed='')
01:22:18 - INFO    - normcap.ocr.magics.email_magic:35 - 0 emails found ['']
01:22:18 - DEBUG   - normcap.ocr.magics.email_magic:46 - 0/61 (0.0) chars in emails
01:22:18 - INFO    - normcap.ocr.magics.url_magic:55 - 0 URLs found ['']
01:22:18 - DEBUG   - normcap.ocr.magics.url_magic:65 - 0/61 (0.0) chars in urls
01:22:18 - DEBUG   - normcap.ocr.magics.magic:77 - Magic scores:
{'SingleLineMagic': 50, 'MultiLineMagic': 0, 'ParagraphMagic': 0.0, 'EmailMagic': 0.0, 'UrlMagic': 0.0}
01:22:18 - DEBUG   - normcap.ocr.recognize:57 - Parsed text:
2€T LEVEL OT deldliL TOr consoLe outputct (aerauLrt: warnwng)
01:22:18 - DEBUG   - normcap.gui.tray:43 - Save debug image as /tmp/normcap/2023-04-25_01-22-18_791696_enhanced.png
01:22:18 - INFO    - normcap.gui.tray:373 - Text from OCR:
2€T LEVEL OT deldliL TOr consoLe outputct (aerauLrt: warnwng)
01:22:18 - DEBUG   - normcap.clipboard.linux:34 - Select clipboard method wl-copy
01:22:18 - DEBUG   - normcap.gui.tray:401 - Copy text to clipboard
01:22:18 - DEBUG   - normcap.gui.notifier:85 - Send notification via notify-send
01:22:24 - INFO    - normcap.gui.tray:443 - Exit normcap (notification sent delaying exit)
01:22:24 - DEBUG   - normcap.gui.tray:444 - Debug images saved in /tmp/normcap
```

**Comment by dynobo** [comment]
Hi @Shaurya-Kalia, thanks for reporting this issue! :+1: 

I was able to reproduce it on a current Manjaro Linux. Seem like the combination of "KDE + Wayland + Launched via Shortcut" is required to trigger this issue.

While debugging, I noticed a strange behavior: I added the shortcut via "Add Command", as I wanted to print the debugging log to a file, using the command:
```sh
/usr/bin/bash -c "/usr/bin/normcap -v debug 2>&1 | tee ~/normcap.log.txt"
```
But this did not only created the log file, it also solved the issue for me!

However, just running a command like this...
```sh
/usr/bin/bash -c "/usr/bin/normcap -v debug"
```
...doesn't seem to help, it seem like a _piping_ is the magic sauce here! :thinking: 

**So a workaround seems to be to create a shortcut through "Add command", which starts NormCap and pipes its output to `/dev/null`:**
```sh
usr/bin/normcap 2>&1 | tee /dev/null
```

Overall, this is super weird, I bet it has something to do with how `Wayland` grants permissions. To be honest, I don't think I can do much about it from `NormCap`-side, as I think the issues are somewhere upstream...

However, could you please verify, if the workaround also works for you? Because what I certainly _can_ do is documenting this quirk in NormCap's FAQs.

How's your feeling about that? Thanks!

**Comment by Shaurya-Kalia** [comment]
Thank you for workaround. I am currently away from my linux machine and will update my observations by tomorrow.

I think it must be reported to kde too, since it would not be limited to normcap alone. Should i post it to kde bugzilla after confirming workaround tomorrow? I would like if you add a bit of technical context to it too since i am much more novice in that regard

**Comment by Shaurya-Kalia** [comment]
> However, could you please verify, if the workaround also works for you? Because what I certainly can do is documenting this quirk in NormCap's FAQs.

I can verify it does work when I use command `normcap | tee /dev/null` (the command `normcap 2>&1 | tee /dev/null` could not be added through system setting's interface).

I also created a bug for the same on [KDE Bugzilla](https://bugs.kde.org/show_bug.cgi?id=469238)

**Comment by dynobo** [comment]
Thanks, @Shaurya-Kalia ! I'm going to add the workaround to NormCaps FAQs, soon.

**Comment by dynobo** [comment]
@Ruakij , which Linux distro and KDE Plasma are you running on?

**Comment by Ruakij** [comment]
> @Ruakij , which Linux distro and KDE Plasma are you running on?

EndeavourOS (Arch)
KDE Version: 5.27.4
QT Version: 5.15.9
Kernel: 6.2.13-arch1-1

**Comment by Ruakij** [comment]
Okayy, update.

Whilst playing around with the shortcuts and trying to get Debug-output from wl-clipboard as described in the linked issue, i got it working..
I dont know why.. but when piping the stdout from `wl-copy` to anything (i tested null and files), it just works?
Uhh.. yay?

I'll report my findings to wl-clipboard.. maybe it helps.

So yeah, i dont know how normcap does the saving, but if you can, try piping stdout from `wl-copy` to `/dev/null`.
