### ISSUE TITLE
Allow custom save folders

### ISSUE THREAD

**Issue by gonzoknows** [dynobo/normcap#436]
### Describe your problem:

It always saves screenshots to pictures, I want to save them to my screenshots folder

### Solution you'd like to see:

Ability to customize the save location

### Alternatives you considered:

None

### Additional information or remarks:

N/A

**Comment by gonzoknows** [comment]
Yes currently on wayland using Vanilla OS

**Comment by dynobo** [comment]
Thanks for letting me, then I'm closing this issue here for now.
