### ISSUE TITLE
Make notification clickable

### ISSUE THREAD

**Issue by vivadavid** [dynobo/normcap#438]
### What happened?

Hi,

1. I run NormCap.
2. I select some text.
3. I get the Windows 11 notification panel with the recognized text.
4. I click on the panel to read the whole recognized text.
5. Nothing happens: the panel is gone.

I've tried to generate the debug log, but when I type _NormCap.exe -v debug_, the terminal reports an error:

> NormCap.exe : El término 'NormCap.exe' no se reconoce como nombre de un cmdlet, función, archivo de script o programa
> ejecutable.

### How did you install NormCap?

MSI installer (Windows)

### Operating System + Version?

Windows 11 (22H2)

**Comment by dynobo** [comment]
Hi @vivadavid , thanks for reporting. I _think_ there is a misunderstanding: the notification of NormCap is not supposed to be clicked, it will do nothing (the default behavior of Windows might be to close/hide the notification in that case).

The purpose of the notification is purely informational: it notifies the user, when the text recognition finished.

The recognized text just ends up in the system clipboard. To access it, just paste it somewhere, e.g. open "Notepad" an press `<ctrl> + v` (or click "Edit" -> "Paste" in the menu).

Does this help you / solve your issue?

PS: I really like the idea of a clickable notification, but afaik `Qt`, the UI library used to build NormCap, doesn`t support it.

PPS: To get the debug information, you need to specify the full path of `NormCap.exe`, otherwise it is not found. Try pasting the _full_ following line:

```cmd
%LOCALAPPDATA%\Programs\dynobo\NormCap\NormCap.exe -v debug
```
Does this work for you.

**Comment by vivadavid** [comment]
Hi, @dynobo ,

Thank you for your message.

1. I thought it was meant to be clickable. It would certainly be nice if you could implement it, as a way to check the text you've just OCRd. Also, you could manually correct little mistakes and select part of the text if necessary.

2. When I typed _NormCap.exe -v debug_, I was actually in the folder where the file was located: that's why I don't understand why it didn't work. I'll check what I'm doing wrong as far as the terminal is concerned.

**Comment by vivadavid** [comment]
Now that I remember, my intention when clicking on the notification panel was not only to see the text, but also to access the settings. Is there currently a way to change the settings of the programme to, for example, add and remove languages?

**Comment by vivadavid** [comment]
Hi, just a quick note to let you know that next time I need to provide you with a log, I'll be able to do it. On the Windows Terminal, I had opened a tab on the Powershell instead of doing it on the Command Prompt. I was confused with all these different tools.

**Comment by dynobo** [comment]
> Is there currently a way to change the settings of the programme to, for example, add and remove languages?

Yes, the menu is behind the red cog wheel that appears on your main monitor in the top right corner during "capture" (red borders around screen). 

I already know, that this isn't super obvious, #443 tries to mitigate that. However, if you have other ideas how to make NormCap more intuitive, let me know!

**Comment by dynobo** [comment]
This has been implemented for macOS and Windows and released. 

The action when clicking on the notification depends on the detected text-type:
- Single-Line, Multi-Line, Characters: Open as new document in default text editor.
- URLs: Open in new tab in default browser.
- Mail-addresses: Compose a new mail with the default mail app.

It would be great if you could test the new feature in [NormCap v0.5.0-beta1](https://github.com/dynobo/normcap/releases/tag/v0.5.0-beta1) and report back, if you like it.

**Comment by vivadavid** [comment]
Hi,

All three options work fine! Thanks for adding this feature!

**Comment by vivadavid** [comment]
Actually, I've just noticed it doesn't work when raw mode is selected (I've tried all three scenarios: notepad, web browser and e-mail client).

**Comment by dynobo** [comment]
> Actually, I've just noticed it doesn't work when raw mode is selected

Great finding, thanks! 

Obviously, due to the nature of the raw mode it won't detect mails or URLs, so these actions can't be triggered. But instead, all captured text _should_ be shown in the editor. Easy fix, probably can be shipped in the next release :slightly_smiling_face:

**Comment by vivadavid** [comment]
> > Actually, I've just noticed it doesn't work when raw mode is selected
> 
> Great finding, thanks!
> 
> Obviously, due to the nature of the raw mode it won't detect mails or URLs, so these actions can't be triggered. But instead, all captured text _should_ be shown in the editor. Easy fix, probably can be shipped in the next release 🙂

Glad I was able to help and thanks for fixing it! :-)

**Comment by dynobo** [comment]
Implemented for macOS and Windows in the [latest release](https://github.com/dynobo/normcap/releases/latest). 

On Linux, it seems like the [`messageClicked()`](https://doc.qt.io/qt-5/qsystemtrayicon.html#messageClicked) signal is not supported. If someone knows a solution for this, please let me know!
