### ISSUE TITLE
Add introduction on first NormCap start

### ISSUE THREAD

**Issue by dynobo** [dynobo/normcap#443]
A lot of new users are confused in how NormCap works. Some common problems:
- Where are the settings? (Cog wheel; only visible during Capture)
- Where is the resulting text (System Clipboard)

This can be mitigated a bit by providing an introduction screen on first start.

The user should be able to make it "not show again".

**Comment by vivadavid** [comment]
Hi,

To be honest, I couldn't find the settings until you replied on https://github.com/dynobo/normcap/issues/438#issuecomment-1539537511.

Now it's pretty obvious to me that the settings icon is there. I wonder if I didn't see it earlier due to the location of the icon or the design (the colour, in particular).

For me, the perfect location of the settings would be after you have performed the OCR: you click on the notification panel and a window opens to access the text. I know that this hasn't been implemented yet.

In any case, this welcome screen sounds like a good idea.

**Comment by Rishabh-Pahwa** [comment]
Hey @dynobo I'd happy to work on this feature and  was thinking that we could a dialog box that redirects users to a demo video on every startup of the app & if the don't show again checkbox is checked then it wouldn't.
What do you think about it.

**Comment by dynobo** [comment]
Hey @Rishabh-Pahwa, thanks for offering your help, contributions on this topic are very welcome! :slightly_smiling_face: 

Let me draft some of my thoughts here. Please don't see them as given, just as inspiration/consideration to kick-start this:
1. A self contained introduction (which doesn't require opening a link, but gets shipped with NormCap) might be more sustainable, flexible and accessible, because it doesn't rely on a 3rd party platform, can be quickly changed within the repository and doesn't require an internet connection.
2. A video/animated-gif has the benefit of being easy to understand and approachable. On the downside, it needs higher effort (for implementation and maintenance) and necessary instructions (e.g. subtitles) are hard to localize (In midterm, I plan to localize NormCap by offering translations for the Menu etc...).
3. A video/animated-gif also is probably larger in file size, and bloating the package further for something you only are supposed to watch one time, might not be worth it (see previous efforts to _reduce_ the package size #238, #144).
4. A sweetspot could be having some screenshots together with explanations/instructions as translatable text.
5. Content-wise I see two major topics that should be covered:
   1. Basic workflow (Select region -> Wait for notification and/or pink tray icon -> Paste anywhere from clipboard)
   2. How to access the Settings menu

**How do you feel about this? Does this make sense?**

PS: Here's a quick scribble of a first idea:
![idea](https://github.com/dynobo/normcap/assets/11071876/695542b7-c6ed-42e6-9d2f-e26866edfef2)

Different layouts would also be possible, of course:
![alt layout](https://github.com/dynobo/normcap/assets/11071876/32651184-6011-43a5-b576-3f179c38a222)

**Comment by Rishabh-Pahwa** [comment]
Sounds good. I'll start working on this.

**Comment by dynobo** [comment]
Great! Let me know, in case you have a question or need some intermediate feedback etc... :slightly_smiling_face:

**Comment by dynobo** [comment]
Hi @Rishabh-Pahwa , did you have the opportunity to work on this issue? Otherwise I could gladly take it over.
(I would like to include the feature in the upcoming release, which is planned in the next 1-3 weeks, that's why I'm asking).

**Comment by Rishabh-Pahwa** [comment]
So sorry got occupied with some work. I will start working on this so that you can publish it with the upcoming release.
Just in case i face any issues I'll let you know in 2-3 days.

**Comment by dynobo** [comment]
Hi @Rishabh-Pahwa , don't worry. Since you haven't started yet, would you mind if I take over? Since I have some spare time, it's probably more efficient, if I do it my own. What do you think?

**Comment by Rishabh-Pahwa** [comment]
You are absolutely right! but i REALLY wanted to contribute. If you could give me a brief about how this project operates(like in which file should i add the intro window code) then i can do it in a day or two.  If that works for you , I'll be so glad. However  if you think that you doing it yourself would be more productive then I'll try to find some other issue to contribute to.🙂

**Comment by dynobo** [comment]
> I'll try to find some other issue to contribute to.🙂

I'd actually prefer that. E.g. you could look into https://github.com/dynobo/normcap/issues/444 , which is less time critical for me. Thanks for your understanding and engagement! :slightly_smiling_face:

**Comment by dynobo** [comment]
Implemented in #501
