### ISSUE TITLE
[Windows] Error after update to v0.4.2 - QtCore: The specified module could not be found

### ISSUE THREAD

**Issue by Jeveze** [dynobo/normcap#452]
### What happened?

I've updated from v0.3.15 but no executable was found.
When installing v0.4.1 the executable is present.
NormCap-0.4.2-x86_64-Windows.msi was used.

### How did you install NormCap?

MSI installer (Windows)

### Operating System + Version?

Windows 10

**Comment by dynobo** [comment]
@Jeveze , can you please tell me, how you tried to start NormCap? Via Start Menu? And can you please provide a screenshot of the error message?

**Comment by Jeveze** [comment]
There is no application in the startmenu on v0.4.2 and there is no executable in C:\Users\%user%\AppData\Local\Programs\dynobo\NormCap\

**Comment by dynobo** [comment]
@Jeveze , that's odd, seems like something went pretty wrong during installation. I can't reproduce the issue on my machines.

Could you please check if you find "NormCap" under Windows' "Add/Remove Software"-overview?

If yes, please try to uninstall NormCap completely.

Then re-install with the `NormCap-[...].msi`-installer. Please pay attention if something unusual is happening during the installation process and if the "Installation complete" Message is shown at the end.

Also: Do you have any AntiVirus or something else running that might interfere with an installation? If yes, can you check their logs/notifications?

**Comment by Jeveze** [comment]
I tried upgrading from 0.4.1 to 0.4.2 and received the following the error when opening normcap.exe
`Traceback (most recent call last):
  File "\app\normcap\__main__.py", line 3, in <module>
    from normcap.app import main
  File "\app\normcap\app.py", line 7, in <module>
    from PySide6 import QtCore, QtWidgets
ImportError: DLL load failed while importing QtCore: The specified module could not be found.`


After that, I followed your instructions and completely removed normcap and installed it from scratch.
Now it seems to work fine.

**Comment by dynobo** [comment]
Thanks for letting me know! Seems like [others have similar issues with this update](https://github.com/dynobo/normcap/issues/454), too. This is super strange, as especially the update from 0.4.1 to 0.4.2 had only very minor, seemingly unrelated changes... :thinking:

**Comment by dynobo** [comment]
I now reproduced the bug by installing v0.4.1 fresh, and then updating (over-install) v04.2.

**I also confirmed, that the a clean install (uninstall v0.4.1, then install v0.4.2) is a viable workaround! I recommend doing that to everyone affected.**

The cause for this is not yet clear to me, but here some observations:

1. Some qt-plugin folders are missing when doing an _update_ (left) vs. a _clean_ install (right).
![Screenshot from 2023-06-03 17-23-41](https://github.com/dynobo/normcap/assets/11071876/45f893ed-d6b3-4808-abea-a78efbfc1386)

2. The missing folder were also present in v0.4.1 (left) before the update to v0.4.2 (right).
![image](https://github.com/dynobo/normcap/assets/11071876/530551fa-45c3-476c-bed1-e028a4a791c8)

I'll need to do some further investigations, maybe I get create some install-logs or something.

**Comment by dynobo** [comment]
Some related SO:
- [File of a new component isn't installed because there was an old component with the same file](https://stackoverflow.com/questions/60827039/file-of-a-new-component-isnt-installed-because-there-was-an-old-component-with)
- [wix major upgrade not installing all files](https://stackoverflow.com/questions/15138731/wix-major-upgrade-not-installing-all-files)

**Comment by dynobo** [comment]
Fix implemented. With the upcoming NormCap v0.4.3 this hopefully should not be an issue anymore.
