### ISSUE TITLE
NormCap-0.4.3-x86_64.AppImage crashs - could not load the qt platform plugin 

### ISSUE THREAD

**Issue by MInessota** [dynobo/normcap#457]
### What happened?

NormCap-0.4.3-x86_64.AppImage is not working.

### How did you install NormCap?

AppImage (Linux)

### Operating System + Version?

Linux Mint 20.3

### [Linux only] Display Server (DS) + Desktop environment (DE)?

e.g. DS: Xorg DE: Cinnamon

### Debug log output?

```shell
./NormCap-0.4.3-x86_64.AppImage -v debug

18:25:48 - INFO    - normcap:30 - Start NormCap v0.4.3
18:25:48 - ERROR   - normcap:214 - [QT] qtinfomsg - could not load the qt platform plugin "xcb" in "" even though it was found.
18:25:48 - ERROR   - normcap:219 - Try solving the problem as described here: ('https://github.com/dynobo/normcap/blob/main/FAQ.md#linux-could-not-load-the-qt-platform-plugin-xcb',)
18:25:48 - ERROR   - normcap:220 - If that doesn't help, please open an issue: https://github.com/dynobo/normcap/issues
18:25:48 - ERROR   - normcap:214 - [QT] qtfatalmsg - this application failed to start because no qt platform plugin could be initialized. reinstalling the application may fix this problem.

available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vkkhrdisplay, vnc, wayland-egl, wayland, xcb.

/tmp/.mount_NormCaxgqKwZ/AppRun, line 11: 43739 Aborted (core image saved) "${APPDIR}/usr/python/bin/python3" -u -s -X utf8 -c "import runpy, sys; sys. path.pop(0); runpy.run_module('${BRIEFCASE_MAIN_MODULE}', run_name='__main__', alter_sys=True)" "$@"
```

**Comment by dynobo** [comment]
Can reproduce on LinuxMint 20.3, and I wouldn't be surprised if every distro based on Ubuntu 20.04 is affected.
I strongly suspect 4b6e20cb2bbefcece7991cf36736eb852124aa8f ,  which updates PySide6 (the QT Python bindings) from 6.4.2 to 6.5.1. 

Investigating...

**Comment by dynobo** [comment]
Seems like [Qt 6.5 requires Ubuntu 22.04+](https://doc.qt.io/qt-6/supported-platforms.html), while [Qt 6.4 was happy with Ubuntu 20.04+](https://doc.qt.io/qt-6.4/supported-platforms.html).

I'm trying to find out, if adding or updating some build or runtime dependencies might help...

**Comment by dynobo** [comment]
@MInessota, a workaround seems to be to install an additional dependency:
```sh
sudo apt install libxcb-cursor0
```

Can you please confirm, that this works for you, too? 

Notes to myself:
- [ ] Investigate if `libxcb-cursor0` can be included in the AppImage
- [ ] Check if this dependency needs to be added somewhere else, too.

**Comment by MInessota** [comment]
Hi dynobo,

It worked installing libxcb-cursor0 (^o^)//

Thank you very much, your program is very good and useful, I use it a lot, it is simple and very practical to use!!!

**Comment by sojusnik** [comment]
Had the same error message when upgrading with `pip install normcap --upgrade` to 0.4.4 on Ubuntu 22.10.

`sudo apt install libxcb-cursor0` helped in this case.
