### ISSUE TITLE
Instructions for installation of windows python package not completely correct.

### ISSUE THREAD

**Issue by bikelif3** [dynobo/normcap#465]
Instructions suggest the following command:
setx TESSDATA_PREFIX "C:\Program Files\Tesseract-OCR\tessdata"

This command created an environment variable in "User variables for Admin" account and not in "system variables". Also, the location should be set to the PARENT of tessdata folder.

I manually created the TESSDATA_PREFIX env variable to the following in "system variables".
TESSDATA_PREFIX
C:\Users\USERNAME\AppData\Local\Programs\Tesseract-OCR

This was the default location UB Mannheim installed to. I also set PATH to the same default location as above.
PATH
C:\Users\USERNAME\AppData\Local\Programs\Tesseract-OCR

Everything works great now. Thanks for the awesome program.

**Comment by dynobo** [comment]
Thanks for reporting this, @bikelif3 !
