### ISSUE TITLE
Trying to Build with Briefcase - Not Working

### ISSUE THREAD

**Issue by Luc8102** [dynobo/normcap#492]
Description
I have made some minor modifications to the code that do not involve new dependencies. I've tested it using
`poetry run normcap`
and there were no errors.
Next, I attempted to build the project on my computer using poetry run briefcase package windows within the top directory of the repository with `poetry run briefcase package windows`.  Ive also tried `briefcase package` The build process completed without any errors.
However, after the build was finished, I received both the installer and the executable. When I double click on the executable, nothing happens. It seems that the application is not launching as expected.

Steps to Reproduce
Make minor modifications to the code.
Run poetry run normcap to ensure the code runs without errors.
Build the project using poetry run briefcase package windows.
After the build is complete, attempt to launch the executable on a Windows machine.
Expected Behavior
The executable should launch successfully, and the application should start running.

Actual Behavior
After double-clicking on the executable, the application does not launch, and there are no error messages.

Additional Information
Operating System: Windows 10
Python version: 3.10.11
Poetry version: 1.5.1
Briefcase version: 0.3.15
Please let me know if there are additional instructions or if I am missing something in the build process. Any help would be appreciated. Thank you!

**Comment by dynobo** [comment]
Hi @Luc8102 , thanks for reporting your issue.

> Next, I attempted to build the project on my computer using poetry run briefcase package windows within the top directory of the repository with poetry run briefcase package windows

Unfortunately, creating the prebuilt packages of Normcap is more complex than just running `briefcase`...

For anyone trying to do this, I recommend to use the github action config in [python.yaml](https://github.com/dynobo/normcap/blob/main/.github/workflows/python.yaml) as starting point. It is used to create the official prebuilt packages and always should reflect the latest working state.

In particular, I recommend looking at the [build-packages job](https://github.com/dynobo/normcap/blob/main/.github/workflows/python.yaml#L180) which contains the steps necessary for the different operating systems. There you can also see, that actually [bundle/build.py](https://github.com/dynobo/normcap/blob/main/bundle/build.py) is called to produce the builds. This script included various prerequisites and hacks to actually package NormCap with `briefcase`.

As the `build.py`-script is quite complex on its own and often requires changes for new releases of `briefcase`, I'm very open for suggestions on how to simplify this process. If anybody has any ideas, please let me know!

@Luc8102 , does this explanation help you?

**Comment by Luc8102** [comment]
Hello @dynobo.  Thank you vey much for getting back to me swiftly.  I did the `poetry run python bundle/build.py --framework=briefcase --dev` in the file and it works now!

Thank you!
