### ISSUE TITLE
Text selection does not always show

### ISSUE THREAD

**Issue by zany130** [dynobo/normcap#494]
### What happened?

Sometimes ( other times it works as expected) running the app does not bring up the text selection window and the tray icon stays white.

### How did you install NormCap?

AUR (Linux)

### Operating System + Version?

Garuda Linux

### [Linux only] Display Server (DS) + Desktop environment (DE)?

DS: Wayland DE KDE

### Debug log output?

```shell
20:41:49 - INFO    - normcap:30 - Start NormCap v0.4.4
20:41:49 - DEBUG   - normcap:86 - Set QT_QPA_PLATFORM=wayland
20:41:49 - DEBUG   - normcap.gui.tray:60 - System info:
{'cli_args': '/usr/bin/normcap -v debug', 'is_briefcase_package': False, 'is_flatpak_package': False, 'platform': 'linux', 'pyside6_version': '6.5.2', 'qt_version': '6.5.2', 'qt_library_path': '/usr/lib/qt6/plugins, /usr/bin', 'config_directory': PosixPath('/home/zany130/.config/normcap'), 'normcap_version': '0.4.4', 'ressources_path': PosixPath('/usr/lib/python3.11/site-packages/normcap/resources'), 'tesseract_path': PosixPath('/usr/bin/tesseract'), 'tessdata_path': None, 'envs': {'TESSDATA_PREFIX': None, 'LD_LIBRARY_PATH': None}, 'desktop_environment': <DesktopEnvironment.KDE: 2>, 'display_manager_is_wayland': True, 'screens': [Screen(is_primary=True, device_pixel_ratio=2.0, rect=Rect(left=3072, top=746, right=5120, bottom=1610), index=0, screenshot=None), Screen(is_primary=False, device_pixel_ratio=3.0, rect=Rect(left=0, top=0, right=1536, bottom=864), index=1, screenshot=None), Screen(is_primary=False, device_pixel_ratio=2.0, rect=Rect(left=1536, top=387, right=3072, bottom=1251), index=2, screenshot=None)]}
20:41:49 - DEBUG   - normcap.gui.tray:342 - Listen on local socket v0.4.4-normcap.
20:41:49 - DEBUG   - normcap.gui.settings:128 - Skip update of non existing setting (cli_mode: False)
20:41:49 - DEBUG   - normcap.gui.settings:128 - Skip update of non existing setting (background_mode: False)
20:41:49 - DEBUG   - normcap.screengrab:37 - Select capture method DBUS portal
20:41:49 - DEBUG   - normcap.screengrab.dbus_portal:196 - Request screenshot with interactive=False
20:41:49 - DEBUG   - normcap.screengrab.dbus_portal:79 - Request accepted
20:41:49 - DEBUG   - normcap.ocr.tesseract:23 - Tesseract command output:
List of available languages in "/usr/share/tessdata/" (2):
eng
osd
20:41:56 - ERROR   - normcap.screengrab.dbus_portal:88 - No response from xdg-portal within 7s!
20:41:56 - WARNING - normcap.screengrab.dbus_portal:199 - Timeout when taking screenshot!
20:41:56 - WARNING - normcap.screengrab.dbus_portal:204 - Didn't receive screenshot! Are permissions missing or did you cancel the intermediate dialog?
20:41:56 - ERROR   - normcap.gui.tray:428 - Could not grab screenshot.
20:41:57 - DEBUG   - normcap.screengrab.dbus_portal:106 - Parse response
```

**Comment by dynobo** [comment]
Hi @zany130 , thanks for reporting this issue!

The logs clearly shows, that the screenshot taking (via DBUS org.freedesktop.portal.Screenshot) fails. Unfortunately, Waylands screenshot API is really bad and doesn't provide information about the reason for a failed screenshot, but usually this is due to some kind of (internal) permission issues.

Did you observe any patterns in when NormCap _does_ show the text selection UI correctly, and when it _does not_? That might help narrowing the problem down. Does it e.g. depends on _how_ NormCap is launched? (Via cli, shortcut, menu,...)

(We noticed in a similar issue #422, that NormCap isn't able to take the screenshot if it was launched via a KDE Shortcut, but [we found a workaround for that](https://github.com/dynobo/normcap/issues/422#issuecomment-1528986744))

**Comment by zany130** [comment]
Seems to be that same issue need to check if piping fixes it when launched from a key shortcut

But starting it from the terminal works

Something interesting is if I try to start it via a key combo it won't work through any other method until I reboot kde .

Killing the app is not enough it will stay in a "broken" state until a restart of kde

**Comment by dynobo** [comment]
Thanks for your further tests, @zany130. As piping doesn't help, it seems to be a different issue.

I tried to reproduce on a regular Arch with KDE Plasma Desktop on Wayland, but NormCap launches without any issues, from Shortcut as well as from Terminal.

Are you using this "Dr460nized" KDE version from Garuda? In that case, I'd try to reproduce it with that variant.

In the meanwhile, could you try adjusting the  NormCap Shortcut to store the debug output in a text file, and share its content here? E.g. the following command should do it: `normcap -v debug 2>&1 | tee  ~/normcap.log`

**Comment by zany130** [comment]
It's difficult to say if disabling my extra monitors made a difference, as sometimes it does work with all monitors enabled, but it seems like it works more often with a single monitor vs. 3

As for the log

```
cat normcap.log
File: normcap.log
13:44:21 - INFO    - normcap:30 - Start NormCap v0.4.4
13:44:21 - DEBUG   - normcap:86 - Set QT_QPA_PLATFORM=wayland
13:44:21 - DEBUG   - normcap.gui.tray:60 - System info:
{'cli_args': '/usr/bin/normcap -v debug', 'is_briefcase_package': False, 'is_flatpak_package': False, 'pla
tform': 'linux', 'pyside6_version': '6.5.2', 'qt_version': '6.5.2', 'qt_library_path': '/usr/lib/qt6/plugi
ns, /usr/bin', 'config_directory': PosixPath('/home/zany130/.config/normcap'), 'normcap_version': '0.4.4',
 'ressources_path': PosixPath('/usr/lib/python3.11/site-packages/normcap/resources'), 'tesseract_path': Po
sixPath('/usr/bin/tesseract'), 'tessdata_path': None, 'envs': {'TESSDATA_PREFIX': None, 'LD_LIBRARY_PATH':
 None}, 'desktop_environment': <DesktopEnvironment.KDE: 2>, 'display_manager_is_wayland': True, 'screens':
 [Screen(is_primary=True, device_pixel_ratio=2.0, rect=Rect(left=3072, top=699, right=5120, bottom=1563),
index=0, screenshot=None), Screen(is_primary=False, device_pixel_ratio=3.0, rect=Rect(left=0, top=0, right
=1536, bottom=864), index=1, screenshot=None), Screen(is_primary=False, device_pixel_ratio=2.0, rect=Rect(
left=1536, top=355, right=3072, bottom=1219), index=2, screenshot=None)]}
13:44:21 - DEBUG   - normcap.gui.tray:342 - Listen on local socket v0.4.4-normcap.
13:44:21 - DEBUG   - normcap.gui.settings:128 - Skip update of non existing setting (cli_mode: False)
13:44:21 - DEBUG   - normcap.gui.settings:128 - Skip update of non existing setting (background_mode: Fals
e)
13:44:21 - DEBUG   - normcap.screengrab:37 - Select capture method DBUS portal
13:44:21 - DEBUG   - normcap.screengrab.dbus_portal:196 - Request screenshot with interactive=False
13:44:21 - DEBUG   - normcap.screengrab.dbus_portal:79 - Request accepted
13:44:21 - DEBUG   - normcap.ocr.tesseract:23 - Tesseract command output:
List of available languages in "/usr/share/tessdata/" (2):
eng
osd
13:44:28 - ERROR   - normcap.screengrab.dbus_portal:88 - No response from xdg-portal within 7s!
13:44:28 - WARNING - normcap.screengrab.dbus_portal:199 - Timeout when taking screenshot!
13:44:28 - WARNING - normcap.screengrab.dbus_portal:204 - Didn't receive screenshot! Are permissions missi
ng or did you cancel the intermediate dialog?
13:44:28 - ERROR   - normcap.gui.tray:428 - Could not grab screenshot.
13:44:30 - DEBUG   - normcap.screengrab.dbus_portal:106 - Parse response
```
I couldn't get it to fail with a single monitor no matter how many times I tried and rebooted the system.

**Comment by dynobo** [comment]
@zany130, I just had a thought, but it's only a shot in the dark: 

Given that the issue occurs only sometimes in your multi-monitor setup (with 3 displays and relative high resolution), maybe the time your system needs to actually take the screenshot and safe it to disk is just very close to the 7 seconds timeout threshold I defined for NormCap? 

This would explain, why it _sometimes_ works, e.g. depending on your systems load. It also would explain, why it _always_ works in the single monitor setup, as a screenshot should be significantly faster there. 
 
To test this hypothesis, could you please (while NormCap is not running) edit the file
```
/usr/lib/python3.11/site-packages/normcap/screengrab/dbus_portal.py
```
and temporarily change the Line 29 from:
```python
TIMEOUT_SECONDS = 7
```
to 
```python
TIMEOUT_SECONDS = 15
```
?
Please let me know, if this makes any difference!

**Comment by zany130** [comment]
yes that seems to fix it haven't gotten the issue since

**Comment by dynobo** [comment]
Great, I will increase this limit to 10s in the next release then.

Thanks for supporting here with your tests, @zany130! :slightly_smiling_face:

**Comment by dynobo** [comment]
Timeout is increased to 10 seconds in the next release. Feel free to reopen this issue, if you are running a setup where this still is not enough.

**Comment by zany130** [comment]
may be worth looking into making this user configurable maybe. though I think 10s should be enough for most cases
