### ISSUE TITLE
End of lifed KDE in use Flatpak

### ISSUE THREAD

**Issue by MANICX100** [dynobo/normcap#497]
### What happened?

Notice when updating

Info: runtime org.kde.Platform branch 6.4 is end-of-life, with reason:
   We strongly recommend moving to the latest stable version of the Plaform and SDK

Info: applications using this runtime:
   com.github.dynobo.normcap

### How did you install NormCap?

FlatPak (Linux)

### Operating System + Version?

Debian 12

### [Linux only] Display Server (DS) + Desktop environment (DE)?

Xorg + iceWM

**Comment by dynobo** [comment]
Thanks for letting me know, @MANICX100 .
Will update, soon.

**Comment by dynobo** [comment]
Done: https://github.com/flathub/com.github.dynobo.normcap/pull/50
