### ISSUE TITLE
The application cannot scan text under icons

### ISSUE THREAD

**Issue by Pawwwle** [dynobo/normcap#503]
### What happened?

The application cannot scan text under icons on the desktop. It needs improvement.

<img width="960" alt="Zrzut ekranu 2023-08-29 120100" src="https://github.com/dynobo/normcap/assets/115624603/42805615-9b92-4525-a0cf-762e9a614ec4">

<img width="960" alt="Zrzut ekranu 2023-08-29 120259" src="https://github.com/dynobo/normcap/assets/115624603/bc991ee0-aa77-4081-a18a-056426ea26fe">

### How did you install NormCap?

MSI installer (Windows)

### Operating System + Version?

Windows 10/11

**Comment by dynobo** [comment]
Hi @Pawwwle, yes, this kind of use-case (selecting a larger area with mixed text & visuals on a heterogeneous background ) is currently not really support. I just create a new feature request #520, which might partially improve the situation.
Until then, you'd need to select the texts under the icons individually (scan multiple times).

**Some background information:**
Tesseract, the FOSS OCR software that NormCap leverages, is optimized for larger areas of printed text (black on white background, without in-between visuals). While NormCap tries to do _some_ preprocessing to improve the detection, the best results still can be obtained by trying to get as close to the "printed text" as possible. See also the [FAQs for some practical tipps to improve detection accuracy](https://dynobo.github.io/normcap/#faqs-improve-detection).

Does this explain the current situation for you, @Pawwwle? Do you see anything else that can/should be done, beside what's mentioned in #520?

**Comment by Pawwwle** [comment]
This is a very difficult case to scan. I'm glad that the application is being developed. I support you with all my heart. :)

**Comment by dynobo** [comment]
Closing for now in favor of #520.
