### ISSUE TITLE
The application does not remain in Tray after restarting the computer

### ISSUE THREAD

**Issue by Pawwwle** [dynobo/normcap#518]
### Describe your problem:

The application does not remain in Tray after restarting the computer.

### Solution you'd like to see:

An option that allows applications to be nested in the Tray.

### Additional information or remarks:

Adding the application to Autostart does not solve the problem because the scan starts immediately.

**Comment by dynobo** [comment]
Hi @Pawwwle , please use the `--background-mode` flag to start NormCap in background (in tray without capture at start). See also [this entry in the FAQs](https://dynobo.github.io/normcap/#faqs-start-in-background). 
Does that solve this issue?

**Comment by Pawwwle** [comment]
I don't know if I did it right, but it still doesn't work. The application does not remain in the system tray after restarting the computer.

![Zrzut ekranu 2023-09-19 195435](https://github.com/dynobo/normcap/assets/115624603/0f9e46e8-3ba8-4dad-b19c-cac5b5e0f245)

**Comment by dynobo** [comment]
@Pawwwle, which NormCap version are you running? (`normcap.exe --version`).
The switch `--background-mode` was introduced in v0.4.3. If it's not working for you, than that might be a bug. If this is the case, can you please run `normcap.exe -v debug` and post its output here?

**Comment by dynobo** [comment]
Note to myself: I should add an "How to autostart NormCap on boot?" to the FAQs

**Comment by dynobo** [comment]
["How can I run NormCap automatically on system start?"](https://dynobo.github.io/normcap/#faqs-autostart) just got published as entry in the FAQs. If it doesn't work or other concerns arise, please feel free to re-open this issue.
