### ISSUE TITLE
Appimage cannot open missing package extra

### ISSUE THREAD

**Issue by docop** [dynobo/normcap#534]
### What happened?

Hi
 I try out your app over Debian os and the appimage do not want to run. But after looking at closed post, i see extra dep that can help and find out to install :
libxcb-cursor0  . And then it pop up open nicely, Very great indeed.
 I would like to know, do you plan to include this dep : libxcb-cursor0  into the appimage file for the next version ? In order to have a fully true portable soft for any os and without having to install stuff.

Thanks in advance

### How did you install NormCap?

AppImage (Linux)

### Operating System + Version?

Debian12 and ubu22

### Debug log output?*

```shell
tell about missing dependance package, but no list.
```

**Comment by dynobo** [comment]
Hi @docop, thanks for reporting. Yes, indeed, the `libxcb-cursor0` dependency was annoying, it got introduced with a minor update of Qt...

The good news is, that I already included it (80fae7e8d4710b6122f1b8802564bc7ae0012c97), so it will be part of the next version. As this version introduces major changes, my plan is to release a public beta in the next few days. :slightly_smiling_face: 

I'm leaving this issue open, until the beta including `libxcb-cursor0` is released.

**Comment by dynobo** [comment]
For reference: #457

**Comment by docop** [comment]
Amazing ! Will test out next week for sure. great.

**Comment by dynobo** [comment]
@docop, For the new [v0.5.0-beta1](https://github.com/dynobo/normcap/releases/tag/v0.5.0-beta1), I tried to include all necessary libraries into the AppImage. If it works, it won't be necessary to install additional packages.

Would be great if you could give it a try and report back if it works for you (or not :wink: ).

**Comment by docop** [comment]
Hi
 I try out over a debian install without the lib pkg and it did not start. here is:
normcap.exe -v debug

./NormCap-0.5.0-beta1-x86_64.AppImage -v debug
16:15:06 - INFO    - normcap:49 - Start NormCap v0.5.0-beta1
/tmp/.mount_NormCazbIabz/AppRun: line 11:  6645 Segmentation fault      "${APPDIR}/usr/python/bin/python3" -u -s -X utf8 -c "import runpy, sys; sys.path.pop(0); runpy.run_module('${BRIEFCASE_MAIN_MODULE}', run_name='__main__', alter_sys=True)" "$@"

 But, over xubu22.04 with the libxcb-cursor0 pkg installed, the app do not start either and give:
./NormCap-0.5.0-beta1-x86_64.AppImage
/tmp/.mount_NormCaVLikbX/AppRun: line 11: 512258 Segmentation fault      "${APPDIR}/usr/python/bin/python3" -u -s -X utf8 -c "import runpy, sys; sys.path.pop(0); runpy.run_module('${BRIEFCASE_MAIN_MODULE}', run_name='__main__', alter_sys=True)" "$@"

 - when try on the same xubu22.04 it direct open the v0.4.4 and do still work.
  hope that can help..

**Comment by dynobo** [comment]
Thanks, @docop . I get the same segfault on Arch, KDE, too... Seems like something is wrong with the AppImage-packaging... I'll take a look at it!

**Comment by dynobo** [comment]
Finally I found the underlying issue: https://github.com/pypa/manylinux/issues/1545
I pinned the manylinux image used for the AppImage to an older tag and confirmed that the segfault does not occur anymore.

**Comment by dynobo** [comment]
This problem should be fixed with the [latest release](https://github.com/dynobo/normcap/releases/lastest). Could you please confirm?

**Comment by docop** [comment]
Heyy hi just tested and it work perfectly ! You can also dwl language file that do work fine. *before doing a selection, in order to go to setting.  Great app !
