### ISSUE TITLE
Please help by testing 0.5.0-beta1

### ISSUE THREAD

**Issue by dynobo** [dynobo/normcap#536]
NormCap `v0.5.0-beta1` just got published :partying_face: . It includes [many noticable changes](https://github.com/dynobo/normcap/blob/main/CHANGELOG) as well as internal refactorings.

You can support this project by [downloading the pre-release](https://github.com/dynobo/normcap/releases/tag/v0.5.0-beta1), testing it on the system(s) you have available, and reporting your experience:

- **If something does not work**, please  [report it as bug](https://github.com/dynobo/normcap/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=bug_report.yml).
- **If everything seems working**, that's very valuable, too! Please leave a comment right here, including the information:
  - Operating system + version: e.g. Win 11, Ubuntu 22.10, ...
  - (Linux) Desktop Environment: e.g. KDE, Gnome, ...
  - (Linux) Compositor: Xorg or Wayland
- **If you have general thoughts or feedback**, report them as comment right here. 

Thanks for your help! :slightly_smiling_face:

**Comment by vivadavid** [comment]
Hi,

When you get the Information panel and then click on OK, the panel stays there blurry, which affects your OCR operation. The panel should go completely.

![blurry introduction panel](https://github.com/dynobo/normcap/assets/9334287/9d8b21b5-6d55-4344-800b-5321080372fa)

**Comment by dynobo** [comment]
@vivadavid , I already have a delay between closing this window and triggering the screenshot, but obviously it's too short. :see-no-evil: (I guess it depends on the system's animation settings...)

Easy to fix, thanks for reporting it! :+1:

**Comment by vivadavid** [comment]
> @vivadavid , I already have a delay between closing this window and triggering the screenshot, but obviously it's too short. 🙈 (I guess it depends on the system's animation settings...)
> 
> Easy to fix, thanks for reporting it! 👍

You are welcome! Thanks for taking care of it!

**Comment by vivadavid** [comment]
Hi,

I had added a second issue, but I can't find it anywhere, so it looks like I forgot to send it.

It's not a big deal to me and I don't know if it's related to this beta (or whether it has to do with Tesseract), but sometimes several paragraphs are put together into one:

**- This is the captured text:**

![OCRd text](https://github.com/dynobo/normcap/assets/9334287/d35c5394-0e25-4806-bf7a-dc8bee61dde6)

**- And this is the text file produced:**

[OCRd text.txt](https://github.com/dynobo/normcap/files/12841605/OCRd.text.txt)

**Comment by dynobo** [comment]
@vivadavid, thanks for noticing. Yeah, that's already known and tracked in issue #502. I'll try to improve the situation for the 0.5.0 final, but can't promise anything.

**Comment by vivadavid** [comment]
> @vivadavid, thanks for noticing. Yeah, that's already known and tracked in issue #502. I'll try to improve the situation for the 0.5.0 final, but can't promise anything.

Thank you for pointing me to the right thread!

**Comment by asukaminato0721** [comment]
```
❯ ./NormCap-0.5.0-beta1-x86_64.AppImage 
05:32:21 - ERROR   - normcap.screengrab.dbus_portal:135 - Error code 1 received from xdg-portal!
05:32:21 - CRITICAL - normcap:138 - Uncaught exception!
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/.mount_NormCacSODSO/usr/python/lib/python3.10/runpy.py", line 224, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/tmp/.mount_NormCacSODSO/usr/python/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/tmp/.mount_NormCacSODSO/usr/python/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/tmp/.mount_NormCacSODSO/usr/app/normcap/__main__.py", line 6, in <module>
    run()
  File "/tmp/.mount_NormCacSODSO/usr/app/normcap/app.py", line 99, in run
    app, tray = _prepare()
  File "/tmp/.mount_NormCacSODSO/usr/app/normcap/app.py", line 92, in _prepare
    tray = SystemTray(app, vars(args))
  File "/tmp/.mount_NormCacSODSO/usr/app/normcap/gui/tray.py", line 118, in __init__
    if not self._ensure_screenshot_permission():
  File "/tmp/.mount_NormCacSODSO/usr/app/normcap/gui/tray.py", line 402, in _ensure_screenshot_permission
    if screengrab.has_screenshot_permission():
  File "/tmp/.mount_NormCacSODSO/usr/app/normcap/screengrab/permissions.py", line 231, in has_screenshot_permission
    return _dbus_portal_has_screenshot_permission()
  File "/tmp/.mount_NormCacSODSO/usr/app/normcap/screengrab/permissions.py", line 200, in _dbus_portal_has_screenshot_permission
    result = dbus_portal.capture()
  File "/tmp/.mount_NormCacSODSO/usr/app/normcap/screengrab/dbus_portal.py", line 223, in capture
    result = _synchronized_capture(interactive=False)
  File "/tmp/.mount_NormCacSODSO/usr/app/normcap/screengrab/dbus_portal.py", line 200, in _synchronized_capture
    raise error
normcap.screengrab.exceptions.ScreenshotResponseError: Error code 1 received from xdg-portal!
05:32:21 - CRITICAL - normcap:141 - System info: {'normcap_version': '0.5.0-beta1', 'python_version': '3.10.13', 'cli_args': '-c', 'is_briefcase_package': True, 'is_flatpak_package': False, 'platform': 'linux', 'desktop_environment': <DesktopEnvironment.KDE: 2>, 'display_manager_is_wayland': True, 'pyside6_version': '6.5.3', 'qt_version': '6.5.3', 'qt_library_path': '/tmp/.mount_NormCacSODSO/usr/app_packages/PySide6/Qt/plugins, /tmp/.mount_NormCacSODSO/usr/python/bin', 'locale': 'zh_CN', 'config_directory': PosixPath('/home/w/.config/normcap'), 'resources_path': PosixPath('/tmp/.mount_NormCacSODSO/usr/app/normcap/resources'), 'tesseract_path': PosixPath('/tmp/.mount_NormCacSODSO/usr/bin/tesseract'), 'tessdata_path': PosixPath('/home/w/.config/normcap/tessdata'), 'envs': {'TESSDATA_PREFIX': None, 'LD_LIBRARY_PATH': None}, 'screens': [Screen(left=0, top=0, right=1919, bottom=1079, device_pixel_ratio=1.0, index=0, screenshot=None)]}
05:32:21 - CRITICAL - normcap:142 - Unfortunately, NormCap has to be terminated due to an unknown problem.
Please help improve NormCap by reporting this error, including the output above, on
https://github.com/dynobo/normcap/issues/new
Thanks!
```

**Comment by dynobo** [comment]
Closing this, as 0.5.0 [got release](https://github.com/dynobo/normcap/releases/latest). 
Thanks everyone for your help! :blush:
