### ISSUE TITLE
[Feature request] Keyboard shortcut to begin capture when in system tray

### ISSUE THREAD

**Issue by sdasda7777** [dynobo/normcap#538]
### Describe your problem:

I'd like to trigger capture with a keyboard shortcut when the program is already running in the system tray. I'd like to avoid launching the program every time.

### Solution you'd like to see:

I'd like to see an option to do this contained within `normcap`.

### Alternatives you considered:

I understand launching the whole program every time using third party solution effectively does almost the same thing, but it's very different from UX perspective. When the program is running in the system tray, you can always see it and can always easily check what the shortcut is. When using third party solution, you have to remember what you were using for this, how to open its settings, and only then you can see what the shortcut is. Not to mention it's harder to set up for a typical user, and you might completely forget you even have `normcap` installed when not using it daily.

**Comment by sdasda7777** [comment]
It also appears to me that on Windows, keyboard shortcuts created through the properties on a `.lnk` file don't really work in some cases, such as when the current window is full-screened? I first experienced this with Firefox, but verified with Chrome and other programs. Also tested with creating keyboard shortcut to other programs, and those also worked only when the current window wasn't full-screened, so it's not `normcap` specific behaviour.

**Comment by sdasda7777** [comment]
Actually using AutoHotKey is really simple and works really well. I just created `capture.ahk` in `shell:startup` which contains this, and it starts on startup, and from then on I can just press Win+C to start the capture.
```AHK
#c::
Run "[INSTALLATION_FOLDER_HERE]\NormCap.exe"
return
```

**Comment by dynobo** [comment]
Just for reference: 

As this question comes up quite often, I added ["Do not implement hotkey"](https://github.com/dynobo/normcap/blob/main/adr/004-do-not-implement-hotkey.md) as [Architecture Decision Record](https://adr.github.io/). It describes the reasoning for not adding hotkey-configuration in NormCap natively, with pro's and con's.

As always, anyone is invited to challenge this reasoning, but please let's use the [disucussions](https://github.com/dynobo/normcap/discussions) for that.

PS: I will also link the ADR in the FAQs.
