### ISSUE TITLE
Enhancement Suggestion - Add Customizable Hotkeys (Keyboard Shortcuts)

### ISSUE THREAD

**Issue by Cr8zyIvan** [dynobo/normcap#590]
### Describe your problem:

Often times I want to Capture Text in a Dropdown Menu. Having a Hotkey would allow me to Capture the Text in Dropdown Menus while they are rolled down. Having to Click on the Taskbar icon prevents this function.

**Comment by Cr8zyIvan** [comment]
Oh hey, thank you for the reply! I try to avoid assigning Keyboard Shortcuts to or via Desktop Shortcuts. I've tried that in the past and I've waited up to 5 seconds on some occasions for the Desktop Shortcut to Launch.

I'll see if I can't find another OCR that might have that integrated. I will say this, your App has everything I was looking for, except for that one tiny feature. In any case, thank you!

**Comment by dynobo** [comment]
> I've tried that in the past and I've waited up to 5 seconds on some occasions for the Desktop Shortcut to Launch.

Another option which is quite popular on Windows is to use the helper tool [AutoHotkey](https://www.autohotkey.com/). I hope you find a tool/workflow that works for you! :slightly_smiling_face:
