### ISSUE TITLE
Suggest additional package requirement on fedora.

### ISSUE THREAD

**Issue by iamashwin99** [dynobo/normcap#654]
I had to install `libxcrypt-compat` on my fedora system to be able to run the appimage.
Otherwise, I got the following error:

```console
❯ ./NormCap-0.5.8-x86_64.appimage 
/tmp/.mount_NormCac2yO0e/usr/python/bin/python3: error while loading shared libraries: libcrypt.so.1: cannot open shared object file: No such file or directory

```

Should we maybe add `libxcrypt-compat` to the list of suggested packages for fedora? Is there a reason why it should work without it?

**Comment by dynobo** [comment]
Thanks for your comment, @iamashwin99 .

This is a known issue an documented in [this FAQ](https://dynobo.github.io/normcap/faqs/#linux-appimage-error-while-loading-shared-libraries-libcryptso1).

But it might be worth considering to put that info somewhere more prominently...

The AppImage currently can be downloaded from Github Releases, the README and the NormCap Website. Do you have any thoughts on where/how the information can be placed, without distracting the unaffected users too much?

**Comment by iamashwin99** [comment]
Sorry! I missed it.
How about something like https://github.com/dynobo/normcap/pull/655 ?
