### ISSUE TITLE
[Windows] Failed to execute script __main__

### ISSUE THREAD

**Issue by ashishpatel1992** [dynobo/normcap#81]
In windows, you will get the error `Failed to execute script __main__` when instead of `click & drag` the area user simply `clicks on the screen`.
**The error should be handled appropriately.**

![normcap](https://user-images.githubusercontent.com/652311/97530599-7dd9fb00-19d8-11eb-8384-8e0d5e615107.gif)

**Comment by dynobo** [comment]
Should be solved with [release v0.1.5](https://github.com/dynobo/normcap/releases/tag/v0.1.5)
