### ISSUE TITLE
[Feature] Update download notification

### ISSUE THREAD

**Issue by ashishpatel1992** [dynobo/normcap#86]
Check for updates on the Application launch and inform users to download new updates when available.
This will help users enjoy the latest features and enhancements in the application.

As of now, there is no way for users to know if there is a new update for the app, until or unless they visit the GitHub repository.

💡 The idea is to pop up the notification if there is an update and ask the user to `Download` it or `Remind me next time`.
if the user chooses to download it, then it will open a browser window with the download link.

**Comment by dynobo** [comment]
Thanks for the suggestion!

It's not one of my top priorities, though, but I would be happy about an Pull Request for this!

Minimal Requirements for a PR would be:
- No new dependencies
- Version Check can be disabled via command line flag
- Info shown to the user should cover different install methods (pip + executable)
- Unittests for successful & unsucessful network calls (e.g. if currently internet is available)

**Comment by dynobo** [comment]
Oh, and in the meanwhile some ideas for (less convenient) workarounds that effected users might want to try:

- Call `pip install --upgrade normcap` regularly (e.g. crontab or scheduled tasks)
- Subscribe to the [releases](https://github.com/dynobo/normcap/releases) with github account.
- Subscribe to [releases rss feed](https://github.com/dynobo/normcap/releases.atom)

**Comment by dynobo** [comment]
With the [release 0.2.3](https://github.com/dynobo/normcap/releases/tag/v0.2.3) I introduced a basic check for updates. Nothing fancy, just shows a message when a new version is available with a link to the repo. You can enable it in the settings (switched off by default, as it does a request to github or pypi)
