### ISSUE TITLE
Tried launching normcap from terminal on MacOS and was able to see dummy window

### ISSUE THREAD

**Issue by karnsaurabhkumar** [dynobo/normcap#99]
![image](https://user-images.githubusercontent.com/10262962/112722422-80149700-8f2f-11eb-9cde-2583f1292509.png)

**Comment by dynobo** [comment]
Thanks for posting! This is a known issue and tracked in Ticket #97.

Sadly I wasn't able to reproduce it so far (I don't own a Mac and can only test in VM). It would be great if you could skim through the conversation in #97 and see if you can provide additional information about your setup, to help reproduce (and hopefully fix) the problem.
